// ===== 花学社 v12 稳妥版 =====
var BOARDS=[{key:'jinghua',name:'✨精华'},{key:'youxiu',name:'🏆好评'},{key:'note',name:'📒笔记'},{key:'jiqiao',name:'💡技巧'},{key:'tiwen',name:'🙋提问'},{key:'suibi',name:'✍️随笔'},{key:'feihualing',name:'🌸飞花令'},{key:'ruozhiba',name:'🤪弱智吧'},{key:'chigua',name:'🍉吃瓜灌水'},{key:'meishi',name:'🍜美食'}];
var POST_BOARDS=BOARDS.filter(function(b){return b.key!=='jinghua'&&b.key!=='youxiu';});
var ADS=[{t:'📶广电正规卡',s:'39元/月·60G·发全国',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12539&agent_id=2783784'},{t:'📶联通碧海卡',s:'29元/月·110G+100分钟·仅发海南',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12543&agent_id=2783784'},{t:'📶联通大禹卡',s:'39元/月·60G+200分钟·只发重庆',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12542&agent_id=2783784'},{t:'📶广电奔马卡',s:'39元/月·60G·只发陕西',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12540&agent_id=2783784'},{t:'📶联通川速卡',s:'39元/月·60G+50分钟·只发四川',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12541&agent_id=2783784'}];
var COURSES=[{t:'高中数学·基础精讲',s:'B站',p:'bili',u:'https://space.bilibili.com'},{t:'英语语法·从零到通',s:'B站',p:'bili',u:'https://www.bilibili.com'},{t:'物理思维·解题技巧',s:'抖音',p:'douyin',u:'https://www.douyin.com'},{t:'学习方法·高效记忆',s:'抖音',p:'douyin',u:'https://www.douyin.com'}];
var REPORT_REASONS=['辱骂/人身攻击','造谣/诽谤','链接/二维码广告','黄赌毒','政治敏感','广告引流','侵犯隐私','恶意刷屏','其他'];
var HOT_LINKS=[{n:'百度热搜',u:'https://top.baidu.com/board'},{n:'微博热搜',u:'https://s.weibo.com/top/summary'},{n:'抖音热榜',u:'https://www.douyin.com/hot'},{n:'B站热搜',u:'https://www.bilibili.com/v/popular/rank/all'},{n:'知乎热榜',u:'https://www.zhihu.com/hot'},{n:'腾讯新闻',u:'https://news.qq.com'}];
var GROUP_LINKS=[{n:'📢腾讯频道·花学社',u:'https://pd.qq.com/s/he8q7kzm3?b=9'},{n:'💬QQ群·花学交流群',u:'https://qun.qq.com/universal-share/share?ac=1&authKey=1aba71zRbWzorsI0HDNexE225xjziJnCD67y5Uc7ZVPOlQIXv3spYCzX27ZzAKWn&busi_data=eyJncm91cENvZGUiOiI3MzkzMzYwODEiLCJ0b2tlbiI6IjJGK2ZVci9NazE3TEVqZXVTcUhDN2hmQmMyQUNiWXA2MW0wejU2ekc4bytsb0RxZ1VOZDNFMm9qZWV5QjNwamkiLCJ1aW4iOiIyNjI5MTgxNzQ3In0%3D&data=qwk3yj6de7aK__jeez-Czl28fBpOJrnBaPPVnanfnIKpBn_WgrZJ-pTPiT-7KUczKFuimVrahitZ1bkfq4AJXA&svctype=4&tempid=h5_group_info'}];
var TIANAPI_KEY='d6dd74802a387df1bb11649ae7a6afcd';
var RULES='《花学社社区总版规》v2.0\n一、总则：花学社是面向大众学习者的学习交流社区，提倡真诚分享、友善互助、专注学习。注册即视为同意本版规。\n二、账号：一人一号严禁小号；Lv.1新用户24h内仅可浏览。\n三、发帖：内容与板块相符、标题简明、主题帖最低2汉字；禁止水帖/刷屏/恶意填分类。\n四、红线：1.链接/二维码：首次拦截不扣分；24h内累计3次→扣30分+禁言7天；5次以上→永久封号+封设备。2.黄赌毒→清分封号封设备。3.辱骂→首次扣10+禁1天再犯扣20+禁3天。4.造谣→同辱骂。5.政治→扣50封号。6.广告引流→扣10~50+禁言/封号。7.侵犯隐私→扣20+禁3天。8.脚本刷分→清分封号封设备。9.挂机→弹验证码/扣20分。10.刷屏→扣20+禁3天。11.无意义评论24h超10条→扣20+禁3天。12.频繁删帖≥5次→禁1天。13.恶意举报→按引战处理。\n五、奖励：签到+2经验+1硬币（连续7天+1/+2，30天+3/+5）；发帖+1经验+2硬币（日限1）；评论+1经验+1硬币（日限1）；被好评+2经验+2信誉分；解题+5经验+5信誉分（日限2）；邀请+25硬币（月限5）；举报成立+3经验+3信誉分+10硬币；阅读简报+1经验+1硬币（日限1）。\n六、等级：0/30/80/160/300/500/800/1200/1800/2500经验。\n七、硬币：打赏1~10枚/次；硬币商店后期。\n八、信誉分(满分100)：80~100正常；60~80减半；40~60禁3天+人工审核；20~40禁7天+仅浏览；0~20永久禁言。\n九、好评每帖仅1次/日限1次；点赞无限制。\n十、评论删除扣回奖励+50%罚金。\n十一、最终解释权归管理员。';
var WELCOME='📜 红线：链接/二维码累计3次→扣30分+禁7天，5次→封号封设备；黄赌毒→清分封号；辱骂→首次扣10+禁1天再犯扣20+禁3天；政治→扣50封号。\n🪙 每日：签到+1硬币、发帖+2、评论+1、阅读简报+1；日限1次。\n⚡ 每日经验上限4点。\n💯 信誉分满分100，低于80权限受限。\n⛔ 挂机超2h弹验证码。\n👶 Lv.1新用户24h内仅浏览。';
function $(id){return document.getElementById(id);}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function fmt(t){if(!t)return'';var d=new Date(t),n=new Date(),p=function(x){return String(x).padStart(2,'0');};return d.toDateString()===n.toDateString()?p(d.getHours())+':'+p(d.getMinutes()):(d.getMonth()+1)+'月'+d.getDate()+'日';}
function toast(m){var t=$('toast');t.textContent=m;t.style.display='block';setTimeout(function(){t.style.display='none';},2000);}
function did(){var d=localStorage.getItem('did');if(!d){d='dev-'+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem('did',d);}return d;}
function authH(){var h={'apikey':SUPABASE_ANON_KEY,'Content-Type':'application/json'};var t=localStorage.getItem('sb_token');if(t)h['Authorization']='Bearer '+t;return h;}
async function refreshT(){var rt=localStorage.getItem('sb_refresh');if(!rt)throw new Error('no rt');var r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'apikey':SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:rt})});var j=await r.json();if(j&&j.access_token){localStorage.setItem('sb_token',j.access_token);localStorage.setItem('sb_refresh',j.refresh_token);return j.access_token;}throw new Error('refresh failed');}
async function api(path,opt){opt=opt||{};var h=authH();if(opt.headers)for(var k in opt.headers)h[k]=opt.headers[k];var res=await fetch(SUPABASE_URL+path,{...opt,headers:h});if(res.status===401){try{await refreshT();var h2=authH();if(opt.headers)for(var k2 in opt.headers)h2[k2]=opt.headers[k2];res=await fetch(SUPABASE_URL+path,{...opt,headers:h2});}catch(e){logout();throw new Error('登录已过期');}}if(!res.ok){var m='HTTP '+res.status;try{var j=await res.json();m=j.msg||j.message||j.hint||m;}catch(e){}throw new Error(m);}var txt=await res.text();if(!txt)return null;try{return JSON.parse(txt);}catch(e){return txt;}}
function qs(o){var r=[];for(var k in o)r.push(encodeURIComponent(k)+'='+encodeURIComponent(o[k]));return r.join('&');}
function dbI(t,b){return api('/rest/v1/'+t,{method:'POST',headers:{'Prefer':'return=representation'},body:JSON.stringify(b)});}
function dbU(t,f,b){return api('/rest/v1/'+t+'?'+f,{method:'PATCH',headers:{'Prefer':'return=representation'},body:JSON.stringify(b)});}
function dbD(t,f){return api('/rest/v1/'+t+'?'+f,{method:'DELETE'});}
function dbR(f,a){return api('/rest/v1/rpc/'+f,{method:'POST',body:JSON.stringify(a||{})});}
function expLv(l){var t={1:0,2:30,3:80,4:160,5:300,6:500,7:800,8:1200,9:1800,10:2500};return t[l]||2500;}
function applyBg(){var b=localStorage.getItem('hxs_bg')||'';document.body.style.background=b||'#F0E6FF';}

var curBoard='jinghua',curPost=null,me=null,sort='new',tipAmt=1,rank='good',resType='video',favType='app',searching=false,isReg=false,captcha='',adIdx=0,adT=null,cmImg=null,curUser=null,replyTo=null,afkT=null,afkC='',spT=null,pomoT=null,pomoL=1500;

applyBg();
function goPage(id){document.querySelectorAll('.page').forEach(function(p){p.classList.remove('active');});$(id).classList.add('active');document.querySelectorAll('#bottomNav .nav-item').forEach(function(n){n.classList.toggle('on',n.dataset.p===id);});if(id==='mainPage'){if(!searching)loadPosts();}else if(id==='postPage'){if(me)initPost();else needLogin();}else if(id==='mePage'){if(me){loadMe();loadHistory();}else needLogin();}else if(id==='editPage'){if(me)initEdit();else needLogin();}else if(id==='invitePage'){if(me)loadInvite();else needLogin();}else if(id==='groupPage')loadGroup();else if(id==='signPage'){if(me)loadSign();else needLogin();}else if(id==='rankPage')loadRank(rank);else if(id==='rulesPage')$('rulesBox').innerHTML=RULES.replace(/\n/g,'<br>');else if(id==='resourcePage'){loadRes(resType);$('resPostBtn').style.display=(me&&me.role==='admin')?'block':'none';}else if(id==='resPostPage'){if(me&&me.role==='admin')initResPost();else needLogin();}else if(id==='adminPage'){if(me&&me.role==='admin')loadAdmin('reports');else needLogin();}else if(id==='coursePage')renderCourses();else if(id==='infoPage'){if(me)loadInfo();else needLogin();}else if(id==='favPage'){if(me)loadFavs(favType);else needLogin();}else if(id==='pomoPage')pomoRender();if(id!=='detailPage'){$('cmBar').style.display='none';replyTo=null;}}
document.querySelectorAll('#bottomNav .nav-item').forEach(function(n){n.onclick=function(){goPage(n.dataset.p);};});
function needLogin(){goPage('loginPage');}
function goMe(){if(me)goPage('mePage');else needLogin();}
function goPost(){if(me)goPage('postPage');else{toast('请先登录');needLogin();}}
function goInfo(){if(me)goPage('infoPage');else needLogin();}
function goGuest(){me=null;localStorage.removeItem('sb_token');localStorage.removeItem('sb_refresh');localStorage.removeItem('sb_user');goPage('mainPage');initAds();loadSpot();}
function exitDetail(){goPage('mainPage');$('cmBar').style.display='none';replyTo=null;}
function closeWelcome(){$('welcomeModal').classList.remove('show');}

function rCode(){var s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',r='';for(var i=0;i<4;i++)r+=s[Math.floor(Math.random()*s.length)];return r;}
function drawCaptcha(){captcha=rCode();var c=$('captcha'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#eef2f7';x.fillRect(0,0,c.width,c.height);for(var i=0;i<3;i++){x.strokeStyle='#c9d4e0';x.beginPath();x.moveTo(Math.random()*c.width,Math.random()*c.height);x.lineTo(Math.random()*c.width,Math.random()*c.height);x.stroke();}x.font='bold 22px Arial';for(var i=0;i<captcha.length;i++){x.fillStyle=['#7B68EE','#e5484d','#ff9500','#6A5ACD'][i%4];x.save();x.translate(18+i*20,26);x.rotate((Math.random()-0.5)*0.4);x.fillText(captcha[i],0,0);x.restore();}}
function toggleReg(){isReg=!isReg;$('loginName').style.display=isReg?'block':'none';$('loginPass2').style.display=isReg?'block':'none';$('loginInvite').style.display=isReg?'block':'none';$('captchaRow').style.display=isReg?'block':'none';$('loginBtn').textContent=isReg?'注 册':'登 录';$('regToggle').textContent=isReg?'已有账号？登录':'没有账号？注册';$('loginErr').textContent='';if(isReg)drawCaptcha();}
function fakeEmail(qq){return 'qq'+qq.trim()+'@qq.local';}
async function doLogin(){var qq=$('loginQQ').value.trim(),pass=$('loginPass').value,err=$('loginErr');if(!/^\d{5,12}$/.test(qq)){err.textContent='请输入正确的QQ号';return;}if(pass.length<6){err.textContent='密码至少6位';return;}var email=fakeEmail(qq);try{if(isReg){var name=$('loginName').value.trim(),p2=$('loginPass2').value,inv=$('loginInvite').value.trim();if(name.length<2||name.length>12){err.textContent='用户名2~12个字';return;}if(pass!==p2){err.textContent='两次密码不一致';return;}if(!captcha||$('loginCaptcha').value.trim().toUpperCase()!==captcha){err.textContent='验证码错误';drawCaptcha();return;}var r=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email:email,password:pass,data:{nickname:name,qq:qq}})});if(r&&r.access_token){localStorage.setItem('sb_token',r.access_token);localStorage.setItem('sb_refresh',r.refresh_token);localStorage.setItem('sb_user',JSON.stringify(r.user));await afterLogin(r.user);if(inv)dbR('apply_invite',{p_invite_code:inv.toUpperCase()}).then(function(x){if(x==='OK')toast('🎉邀请成功+25硬币');}).catch(function(){});}else{err.textContent='注册失败：该QQ号可能已注册';}}else{var r2=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:email,password:pass})});if(r2&&r2.access_token){localStorage.setItem('sb_token',r2.access_token);localStorage.setItem('sb_refresh',r2.refresh_token);localStorage.setItem('sb_user',JSON.stringify(r2.user));afterLogin(r2.user);}else{err.textContent='登录失败：QQ号或密码错误，未注册请先注册';}}}catch(e){err.textContent='操作失败：'+e.message;}}
async function afterLogin(u){try{var b=await dbR('is_device_banned',{dev:did()});if(b){logout();toast('🚫该设备已被封禁');return;}await dbU('profiles','id=eq.'+u.id,{device_id:did()});}catch(e){}showMain();}
function logout(){localStorage.removeItem('sb_token');localStorage.removeItem('sb_refresh');localStorage.removeItem('sb_user');location.reload();}
function curUser2(){try{return JSON.parse(localStorage.getItem('sb_user'));}catch(e){return null;}}
async function fetchMe(){var u=curUser2();if(!u)return null;try{var r=await api('/rest/v1/profiles?select=*&id=eq.'+u.id);return r&&r[0]||null;}catch(e){return null;}}
async function showMain(){me=await fetchMe();if(!me)me={nickname:'花友',level:1,exp:0,coins:0,credit:100,role:'user'};$('topAvatar').textContent=me.nickname?me.nickname[0]:'友';loadInfoCount();goPage('mainPage');initAds();loadSpot();resetAfk();if(!localStorage.getItem('hxs_welcomed')){$('welcomeBody').innerHTML=WELCOME.replace(/\n/g,'<br>');$('welcomeModal').classList.add('show');localStorage.setItem('hxs_welcomed','1');}}

function resetAfk(){if(afkT)clearTimeout(afkT);afkT=setTimeout(function(){showAfk();},7200000);}
function showAfk(){$('afkOverlay').classList.add('show');drawAfkCaptcha();}
function drawAfkCaptcha(){afkC=rCode();var c=$('afkCaptcha'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#eef2f7';x.fillRect(0,0,c.width,c.height);for(var i=0;i<4;i++){x.strokeStyle='#c9d4e0';x.beginPath();x.moveTo(Math.random()*c.width,Math.random()*c.height);x.lineTo(Math.random()*c.width,Math.random()*c.height);x.stroke();}x.font='bold 24px Arial';for(var i=0;i<afkC.length;i++){x.fillStyle=['#7B68EE','#e5484d','#ff9500','#6A5ACD'][i%4];x.save();x.translate(24+i*24,28);x.rotate((Math.random()-0.5)*0.4);x.fillText(afkC[i],0,0);x.restore();}}
function checkAfk(){if($('afkInput').value.trim().toUpperCase()===afkC){$('afkOverlay').classList.remove('show');$('afkInput').value='';resetAfk();}else{toast('验证码错误');drawAfkCaptcha();}}
['click','keydown','scroll'].forEach(function(e){document.addEventListener(e,resetAfk);});

function initAds(){$('adTrack').innerHTML=ADS.map(function(a){return '<div class="ad-item" onclick="location.href=\''+a.u+'\'"><div style="font-size:14px;font-weight:700">'+a.t+'</div><div style="font-size:12px;opacity:.9;margin-top:2px">'+a.s+'</div></div>';}).join('');$('adDots').innerHTML=ADS.map(function(_,i){return '<span class="'+(i===0?'on':'')+'"></span>';}).join('');adIdx=0;if(adT)clearInterval(adT);adT=setInterval(function(){adIdx=(adIdx+1)%ADS.length;$('adTrack').style.transform='translateX(-'+(adIdx*100)+'%)';document.querySelectorAll('#adDots span').forEach(function(s,i){s.classList.toggle('on',i===adIdx);});},4000);}

async function loadSpot(){if(curBoard!=='jinghua'){$('spotlight').style.display='none';return;}$('spotlight').style.display='block';var h='<div class="dc-grad">🌸 每日速递</div>';
try{var n=await fetch('https://api.magicalbox.cn/api3/tool/api/getMorningPaper');var nj=await n.json();if(nj&&nj.data){h+='<div class="dc-card"><div class="dc-h">» 60秒早报 <span style="margin-left:auto;color:#999;font-size:10px">'+nj.data.date+'</span></div>';var arr=nj.data.news||[];for(var i=0;i<arr.length&&i<12;i++){h+='<div class="dc-item" onclick="toast(this.textContent)"><b>'+(i+1)+'.</b> '+esc(arr[i])+'</div>';}if(nj.data.image)h+='<div class="dc-item" style="color:#7B68EE" onclick="window.open(\''+nj.data.image+'\')">🖼️ 查看完整早报图 →</div>';h+='</div>';}}catch(e){}
try{var e=await fetch('https://apiv3.shanbay.com/weapps/dailyquote/quote');var ej=await e.json();if(ej&&ej.content)h+='<div class="dc-card"><div class="dc-h">» 每日英语</div><div class="dc-en">"'+esc(ej.content)+'"</div>'+(ej.translation?'<div class="dc-cn">'+esc(ej.translation)+(ej.author?' · '+esc(ej.author):'')+'</div>':'')+'</div>';}catch(e){}
try{var q=await fetch('https://v1.hitokoto.cn/');var qj=await q.json();if(qj&&qj.hitokoto)h+='<div class="dc-card"><div class="dc-h">» 每日一言</div><div class="dc-quote">"'+esc(qj.hitokoto)+'"</div>'+(qj.from?'<div class="dc-cn" style="text-align:center">—— '+esc(qj.from)+'</div>':'')+'</div>';}catch(e){}
try{var nw=await fetch('https://apis.tianapi.com/generalnews/index?key='+TIANAPI_KEY+'&num=8');var nwj=await nw.json();if(nwj&&nwj.code===200&&nwj.result&&nwj.result.newslist){h+='<div class="dc-card"><div class="dc-h">» 新闻资讯</div>';nwj.result.newslist.forEach(function(n,i){h+='<div class="dc-item" onclick="window.open(\''+n.url+'\')"><b>'+(i+1)+'.</b> '+esc(n.title)+'</div>';});h+='</div>';}}catch(e){}
try{var g=await fetch('http://8.134.118.1:9090/days/apps/getHistory');var gt=await g.text();var parts=gt.split('%%%').filter(function(x){return x.trim()&&x.trim()!=='true';});var hi=0;h+='<div class="dc-card"><div class="dc-h">» 历史上的今天</div>';parts.forEach(function(p){try{var j=JSON.parse(p.trim());if(j&&j.title&&hi<5){h+='<div class="dc-item" onclick="window.open(\''+(j.link||'')+'\')"><b>'+esc(String(j.year||'').replace('年',''))+'</b>· '+esc(String(j.title).replace(/<[^>]+>/g,''))+'</div>';hi++;}}catch(e){}});h+='</div>';}catch(e){}
try{var bh=await fetch('https://apis.tianapi.com/networkhot/index?key='+TIANAPI_KEY);var bhj=await bh.json();if(bhj&&bhj.code===200&&bhj.result&&bhj.result.list){h+='<div class="dc-card"><div class="dc-h">» 百度热搜 TOP10</div>';bhj.result.list.slice(0,10).forEach(function(r,i){h+='<div class="dc-item" onclick="window.open(\'https://www.baidu.com/s?wd='+encodeURIComponent(r.keyword)+'\')"><b>'+(i+1)+'.</b> '+esc(r.keyword)+'</div>';});h+='</div>';}}catch(e){}
try{var wh=await fetch('https://apis.tianapi.com/weibohot/index?key='+TIANAPI_KEY);var whj=await wh.json();if(whj&&whj.code===200&&whj.result&&whj.result.list){h+='<div class="dc-card"><div class="dc-h">» 微博热搜 TOP10</div>';whj.result.list.slice(0,10).forEach(function(r,i){h+='<div class="dc-item" onclick="window.open(\'https://s.weibo.com/weibo?q='+encodeURIComponent(r.hotword)+'\')"><b>'+(i+1)+'.</b> '+esc(r.hotword)+'</div>';});h+='</div>';}}catch(e){}
$('spotlight').innerHTML=h;if(spT)clearInterval(spT);spT=setInterval(function(){if(curBoard==='jinghua')loadSpot();},28800000);}
function quickPost(t){toast(t);}

function renderBoards(){$('boards').innerHTML=BOARDS.map(function(b){return '<div class="board-tab '+(b.key===curBoard&&!searching?'on':'')+'" data-k="'+b.key+'">'+b.name+'</div>';}).join('');$('boards').querySelectorAll('.board-tab').forEach(function(t){t.onclick=function(){searching=false;$('searchInput').value='';curBoard=t.dataset.k;renderBoards();loadPosts();};});}
function doSearch(){searching=true;var kw=$('searchInput').value.trim();$('postList').innerHTML='<div class="empty">搜索中...</div>';api('/rest/v1/posts?select=*,author_id(nickname,level,qq,id)&status=eq.published&or=(title.ilike.*'+encodeURIComponent(kw)+'*,content.ilike.*'+encodeURIComponent(kw)+'*)&order=created_at.desc&limit=50').then(function(d){renderCards(d,$('postList'),'没搜到');}).catch(function(){$('postList').innerHTML='<div class="empty">搜索失败</div>';});}
async function loadPosts(){renderBoards();initAds();loadSpot();if(searching){doSearch();return;}$('postList').innerHTML='<div class="empty">加载中...</div>';try{var order='created_at.desc';if(sort==='like')order='like_count.desc';else if(sort==='fav')order='good_count.desc';var cond;if(curBoard==='jinghua'||curBoard==='youxiu')cond=qs({status:'eq.published',is_featured:'eq.true',select:'*,author_id(nickname,level,qq,id)',order:order,limit:'50'});else cond=qs({status:'eq.published',board:'eq.'+curBoard,select:'*,author_id(nickname,level,qq,id)',order:order,limit:'50'});var d=await api('/rest/v1/posts?'+cond);renderCards(d,$('postList'),'这个板块还没有帖子✨');}catch(e){$('postList').innerHTML='<div class="empty">加载失败</div>';}}
$('sortBar').querySelectorAll('span').forEach(function(s){s.onclick=function(){sort=s.dataset.s;$('sortBar').querySelectorAll('span').forEach(function(x){x.classList.toggle('on',x.dataset.s===sort);});loadPosts();};});
function renderCards(d,box,emptyTxt){if(!d||!d.length){box.innerHTML='<div class="empty">'+(emptyTxt||'暂无')+'</div>';return;}box.innerHTML=d.map(function(p){var img=p.images&&p.images[0]?'<div class="wm"><img class="pc-img" src="'+esc(p.images[0])+'" onerror="this.parentNode.style.display=\'none\'"><div class="watermark">🌸花学社·'+esc(p.author_id?p.author_id.nickname||'':'')+'·'+esc(p.author_id?p.author_id.qq||'':'')+'</div></div>':'';return '<div class="post-card" onclick="openPost('+p.id+')"><div class="pc-title">'+esc(p.title)+(p.is_featured?'🏆':'')+'</div><div class="pc-body">'+esc(p.content)+'</div>'+img+'<div class="pc-meta"><span style="cursor:pointer" onclick="event.stopPropagation();openUser(\''+(p.author_id?p.author_id.id||'':'')+'\')">👤'+esc(p.author_id?p.author_id.nickname||'花友':'花友')+'<span class="lv">Lv'+(p.author_id?p.author_id.level||1:1)+'</span></span><span>👍'+p.like_count+'</span><span>❤️'+p.good_count+'</span><span>🪙'+p.coin_count+'</span><span style="margin-left:auto">'+fmt(p.created_at)+'</span></div></div>';}).join('');}
async function openPost(id){try{var r=await api('/rest/v1/posts?select=*,author_id(nickname,level,qq,id)&id=eq.'+id);if(!r||!r[0])return;curPost=r[0];}catch(e){return;}if(me)dbI('history',{user_id:me.id,post_id:id}).catch(function(){});var d=curPost,fav=me?await isFav('post',d.id):false;var isAuthor=me&&d.author_id&&d.author_id.id===me.id;var img=d.images&&d.images[0]?'<div class="wm" style="margin-top:8px"><img src="'+esc(d.images[0])+'" style="width:100%;border-radius:8px" onerror="this.parentNode.style.display=\'none\'">'+(isAuthor?'':'<div class="watermark">🌸花学社·'+esc(d.author_id?d.author_id.nickname||'':'')+'·'+esc(d.author_id?d.author_id.qq||'':'')+'</div>')+'</div>':'';var acts='<div class="detail-actions"><button class="action-btn '+(isLiked(d.id)?'on':'')+'" onclick="likePost()">👍'+d.like_count+'</button><button class="action-btn" style="border-color:#ff9500;color:#ff9500" onclick="openTip()">🎁打赏</button><button class="action-btn" onclick="openReport(\'post\','+d.id+')">🚩举报</button><button class="action-btn '+(fav?'on':'')+'" style="border-color:#7B68EE;color:#7B68EE" onclick="toggleFav()">⭐'+(fav?'已收藏':'收藏')+'</button>';if(isAuthor||(me&&me.role==='admin'))acts+='<button class="action-btn" style="color:#e5484d" onclick="deletePost('+d.id+')">🗑删除</button>';acts+='</div>';if(me&&me.role==='admin')acts+='<div class="detail-actions"><button class="action-btn" onclick="toggleFeatured()">'+(d.is_featured?'移出':'加入')+'精华</button></div>';$('detailBox').innerHTML='<div class="detail-title">'+esc(d.title)+(d.is_featured?'🏆':'')+'</div><div class="detail-meta"><span style="cursor:pointer" onclick="openUser(\''+(d.author_id?d.author_id.id||'':'')+'\')">👤'+esc(d.author_id?d.author_id.nickname||'花友':'花友')+'</span><span class="lv">Lv'+(d.author_id?d.author_id.level||1:1)+'</span><span style="margin-left:auto">'+fmt(d.created_at)+'</span></div><div class="detail-body">'+esc(d.content)+'</div>'+img+acts;$('cmBar').style.display=me?'flex':'none';replyTo=null;loadComments(id);goPage('detailPage');}
function isLiked(id){return(JSON.parse(localStorage.getItem('liked')||'[]')).indexOf(id)>-1;}
async function likePost(){if(!me){toast('请先登录');needLogin();return;}var l=JSON.parse(localStorage.getItem('liked')||'[]');if(l.indexOf(curPost.id)>-1)return;l.push(curPost.id);localStorage.setItem('liked',JSON.stringify(l));try{await dbU('posts','id=eq.'+curPost.id,{like_count:curPost.like_count+1});curPost.like_count++;if(curPost.author_id&&curPost.author_id.id!==me.id)dbR('notify_user',{p_user_id:curPost.author_id.id,p_type:'like',p_content:me.nickname+'赞了你的帖子'}).catch(function(){});document.querySelectorAll('.action-btn')[0].classList.add('on');}catch(e){toast('点赞失败');}}
async function toggleFeatured(){if(!me||me.role!=='admin')return;try{await dbU('posts','id=eq.'+curPost.id,{is_featured:!curPost.is_featured});curPost.is_featured=!curPost.is_featured;toast(curPost.is_featured?'已加入精华🏆':'已移出精华');openPost(curPost.id);}catch(e){toast('操作失败');}}
async function deletePost(pid){if(!confirm('确定删除？'))return;try{var r=await dbR('delete_post',{pid:pid});toast(r==='OK'?'✅已删除':('⚠️'+r));if(r==='OK')goPage('mainPage');}catch(e){toast('删除失败：'+e.message);}}

function pickCmImg(){var f=$('cmImg').files&&$('cmImg').files[0];if(!f)return;cmImg=f;$('cmDel').style.display='inline';toast('📷已选图片');}
function cancelCmImg(){cmImg=null;$('cmImg').value='';$('cmDel').style.display='none';toast('已取消');}
function pickImg(inp,prevId){var f=inp.files&&inp.files[0];if(!f)return;var img=URL.createObjectURL(f);$(prevId).innerHTML='<div class="img-preview-wrap"><img src="'+img+'"><span class="cancel-img" onclick="document.getElementById(\''+prevId+'\').innerHTML=\'\'">✕</span></div>';inp._selected=f;}
async function loadComments(pid){try{var d=await api('/rest/v1/comments?select=*,author_id(nickname,level,id)&post_id=eq.'+pid+'&status=eq.published&order=created_at.asc');if(!d||!d.length){$('commentList').innerHTML='<div class="empty" style="padding:14px 0">还没有评论</div>';return;}$('commentList').innerHTML=d.map(function(c){return '<div class="comment-box"><div class="cb-name" onclick="openUser(\''+(c.author_id?c.author_id.id||'':'')+'\')">👤'+esc(c.author_id?c.author_id.nickname||'花友':'花友')+'<span class="lv">Lv'+(c.author_id?c.author_id.level||1:1)+'</span></div><div class="cb-text">'+esc(c.content)+'</div>'+(c.image?'<img class="cb-img" src="'+esc(c.image)+'" onerror="this.style.display=\'none\'">':'')+'<div class="cb-time">'+fmt(c.created_at)+'</div><div class="cb-acts"><span onclick="likeCm('+c.id+')">👍</span><span onclick="favCm('+c.id+')">⭐</span><span onclick="openReport(\'comment\','+c.id+')">🚩</span><span onclick="replyTo('+c.id+',\''+esc(c.author_id?c.author_id.nickname||'':'')+'\')">💬回复</span>'+(me&&(me.id===c.author_id.id||me.role==='admin')?'<span onclick="delCm('+c.id+')">🗑</span>':'')+'</div></div>';}).join('');}catch(e){$('commentList').innerHTML='<div class="empty">加载失败</div>';}}
async function likeCm(cid){if(!me){toast('请先登录');needLogin();return;}try{var cur=await api('/rest/v1/comments?select=like_count&id=eq.'+cid);await dbU('comments','id=eq.'+cid,{like_count:(cur&&cur[0]?cur[0].like_count:0)+1});toast('👍');loadComments(curPost.id);}catch(e){toast('失败');}}
function replyTo(cid,name){if(!me){toast('请先登录');needLogin();return;}replyTo=cid;$('cmInput').placeholder='回复 @'+name;$('cmInput').focus();$('cmBar').style.display='flex';}
async function submitComment(){if(!me){toast('请先登录');needLogin();return;}var c=$('cmInput').value.trim();if(!c&&!cmImg)return;try{var image='';if(cmImg){try{image=await uploadImg(cmImg);}catch(e){toast('图片上传失败');return;}}var r=await dbI('comments',{post_id:curPost.id,author_id:me.id,content:c,image:image,reply_to:replyTo});if(r&&r[0]&&r[0].status==='rejected')toast('🚫'+r[0].reject_reason);else{$('cmInput').value='';$('cmInput').placeholder='友善评论…';cmImg=null;$('cmImg').value='';$('cmDel').style.display='none';replyTo=null;if(curPost.author_id&&curPost.author_id.id!==me.id)dbR('notify_user',{p_user_id:curPost.author_id.id,p_type:'comment',p_content:me.nickname+'评论了你的帖子'}).catch(function(){});loadComments(curPost.id);}}catch(e){toast('发布失败：'+e.message);}}
async function delCm(cid){if(!confirm('确定删除？奖励扣回+50%罚金'))return;try{var r=await dbR('delete_comment',{cid:cid});toast(r==='OK'?'✅已删除':('⚠️'+r));if(r==='OK')loadComments(curPost.id);}catch(e){toast('删除失败');}}
async function favCm(cid){if(!me){toast('请先登录');needLogin();return;}try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.comment&target_id=eq.'+cid+'&limit=1');if(r&&r.length){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.comment&target_id=eq.'+cid);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:'comment',target_id:cid});toast('⭐已收藏');}}catch(e){toast('失败');}}

async function isFav(type,tid){if(!me)return false;try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.'+type+'&target_id=eq.'+tid+'&limit=1');return r&&r.length>0;}catch(e){return false;}}
async function toggleFav(){if(!me){toast('请先登录');needLogin();return;}var fav=await isFav('post',curPost.id);try{if(fav){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.post&target_id=eq.'+curPost.id);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:'post',target_id:curPost.id});toast('⭐已收藏');}openPost(curPost.id);}catch(e){toast('失败');}}
async function loadFavs(type){favType=type;['app','course','post','comment'].forEach(function(t,i){var el=$('favTab'+(i+1));if(el)el.classList.toggle('on',t===type);});$('favList').innerHTML='<div class="empty">加载中...</div>';if(!me){$('favList').innerHTML='<div class="empty">请先登录</div>';return;}var kw=$('favSearch').value.trim();try{var favs=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.'+type+'&order=created_at.desc&limit=100');if(!favs||!favs.length){$('favList').innerHTML='<div class="empty">还没有收藏</div>';return;}if(type==='post'){var ids=favs.map(function(f){return f.target_id;});var posts=await api('/rest/v1/posts?select=*,author_id(nickname,level)&id=in.('+ids.join(',')+')&status=eq.published');var items=posts||[];if(kw)items=items.filter(function(p){return p.title.indexOf(kw)>-1||p.content.indexOf(kw)>-1;});$('favList').innerHTML=items.length?items.map(function(p){return '<div class="his-card" onclick="openPost('+p.id+')"><span style="flex:1;font-size:13px">'+esc(p.title)+'</span><span style="font-size:10px;color:#bbb">›</span></div>';}).join(''):'<div class="empty">没搜到</div>';}else if(type==='comment'){var ids2=favs.map(function(f){return f.target_id;});var cmts=await api('/rest/v1/comments?select=*,author_id(nickname)&id=in.('+ids2.join(',')+')&status=eq.published');var items2=cmts||[];if(kw)items2=items2.filter(function(c){return c.content.indexOf(kw)>-1;});$('favList').innerHTML=items2.length?items2.map(function(c){return '<div class="comment-box"><div class="cb-text">'+esc(c.content)+'</div><div class="cb-time">👤'+esc(c.author_id?c.author_id.nickname||'':'')+'·'+fmt(c.created_at)+'</div></div>';}).join(''):'<div class="empty">没搜到</div>';}else if(type==='app'){var ids3=favs.map(function(f){return f.target_id;});var res=await api('/rest/v1/resources?type=eq.app&id=in.('+ids3.join(',')+')');var items3=res||[];if(kw)items3=items3.filter(function(r){return r.title.indexOf(kw)>-1||(r.description||'').indexOf(kw)>-1;});$('favList').innerHTML=items3.length?items3.map(function(r){return '<div class="app-card" onclick="openAppDetail('+r.id+')"><div class="ac-top"><div class="ac-icon" style="background:#eee;text-align:center;line-height:48px;font-size:22px">'+(r.icon?'<img src="'+esc(r.icon)+'" class="ac-icon">':'📱')+'</div><div><div class="ac-title">'+esc(r.title)+'</div><div class="ac-sub">'+esc(r.description||'')+'</div></div></div></div>';}).join(''):'<div class="empty">没搜到</div>';}else{var items4=COURSES.filter(function(c,i){return favs.some(function(f){return f.target_id===i;});});var list=kw?items4.filter(function(c){return c.t.indexOf(kw)>-1;}):items4;$('favList').innerHTML=list.length?list.map(function(c){return '<div class="his-card" onclick="location.href=\''+c.u+'\'"><span style="flex:1;font-size:13px">'+esc(c.t)+'</span><span style="font-size:10px;color:#bbb">'+c.s+'</span></div>';}).join(''):'<div class="empty">没搜到</div>';}}catch(e){$('favList').innerHTML='<div class="empty">加载失败</div>';}}

async function uploadImg(file){var name=Date.now()+'-'+Math.random().toString(36).slice(2,6)+'.jpg';var res=await fetch(SUPABASE_URL+'/storage/v1/object/images/'+name,{method:'POST',headers:{...authH(),'Content-Type':file.type||'image/jpeg'},body:file});if(!res.ok){if(res.status===403)throw new Error('Storage权限不足，请跑SQL');if(res.status===404)throw new Error('Storage没有images桶，请创建');throw new Error('上传失败('+res.status+')');}return SUPABASE_URL+'/storage/v1/object/public/images/'+name;}
function initPost(){$('boardChips').innerHTML=POST_BOARDS.map(function(b){return '<div class="chip '+(b.key===curBoard?'on':'')+'" data-k="'+b.key+'">'+b.name+'</div>';}).join('');$('boardChips').querySelectorAll('.chip').forEach(function(x){x.onclick=function(){$('boardChips').querySelectorAll('.chip').forEach(function(y){y.classList.remove('on');});x.classList.add('on');curBoard=x.dataset.k;};});$('postErr').textContent='';$('imgPreview').innerHTML='';}
async function submitPost(){if(!me){toast('请先登录');needLogin();return;}if(me&&me.banned_until&&new Date(me.banned_until)>new Date()){toast('⛔禁言中');return;}if(me&&me.is_banned){toast('⛔已封禁');return;}if(me&&me.level<2&&me.created_at&&new Date()-new Date(me.created_at)<86400000){toast('Lv.1新用户24h内仅浏览');return;}var title=$('pTitle').value.trim(),content=$('pContent').value.trim();if(!title||!content){$('postErr').textContent='请填写标题和内容';return;}if(title.replace(/[a-zA-Z0-9\s]/g,'').length<2){$('postErr').textContent='标题至少2个汉字';return;}var images=[];var f=$('pImg')._selected;try{if(f)images.push(await uploadImg(f));var r=await dbI('posts',{author_id:me.id,board:curBoard,title:title,content:content,images:images});if(r&&r[0]&&r[0].status==='rejected'){$('postErr').textContent='🚫'+r[0].reject_reason;return;}$('postErr').textContent='✅发布成功';$('pTitle').value='';$('pContent').value='';$('pImg').value='';$('pImg')._selected=null;$('imgPreview').innerHTML='';setTimeout(function(){goPage('mainPage');},700);}catch(e){$('postErr').textContent='发布失败：'+e.message;}}

function openTip(){if(!me){toast('请先登录');needLogin();return;}if(curPost.author_id&&curPost.author_id.id===me.id){toast('不能打赏自己');return;}$('tipCoins').innerHTML=[1,2,5,10].map(function(n){return '<div class="chip '+(n===tipAmt?'on':'')+'" data-n="'+n+'" onclick="pickTip('+n+')">🪙'+n+'</div>';}).join('');$('tipModal').classList.add('show');}
function pickTip(n){tipAmt=n;document.querySelectorAll('#tipCoins .chip').forEach(function(c){c.classList.toggle('on',+c.dataset.n===n);});}
function hideTip(){$('tipModal').classList.remove('show');}
async function doTip(kind,amount){try{var r=await dbR('tip_post',{p_post_id:curPost.id,p_kind:kind,p_amount:amount||tipAmt});toast(r||'操作失败');hideTip();setTimeout(function(){openPost(curPost.id);},700);}catch(e){toast('失败：'+e.message);}}
function openReport(type,tid){if(!me){toast('请先登录');needLogin();return;}$('reportReasons').innerHTML=REPORT_REASONS.map(function(r,i){return '<label style="display:block;padding:8px 0;border-bottom:1px solid #f4f4f4;font-size:13px"><input type="checkbox" class="rr" data-r="'+i+'" style="margin-right:8px">'+r+'</label>';}).join('')+'<button class="btn" style="margin-top:10px" onclick="submitReport(\''+type+'\','+tid+')">提交举报</button>';$('reportModal').classList.add('show');}
function hideReport(){$('reportModal').classList.remove('show');}
async function submitReport(type,tid){var sel=[];document.querySelectorAll('.rr:checked').forEach(function(x){sel.push(REPORT_REASONS[+x.dataset.r]);});if(!sel.length){toast('请至少勾选一个原因');return;}try{await dbI('reports',{target_type:type,target_id:tid,reason:sel.join('、'),reporter_id:me.id});toast('🚩举报成功，成立有奖');hideReport();}catch(e){toast('举报失败');}}

async function openUser(uid){if(!uid)return;curUser=uid;try{var r=await api('/rest/v1/profiles?select=*&id=eq.'+uid);var u=r&&r[0];if(!u){toast('用户不存在');return;}var isMe2=me&&me.id===uid;var fol=me?await api('/rest/v1/followers?follower_id=eq.'+me.id+'&following_id=eq.'+uid+'&limit=1'):null;var folN=await api('/rest/v1/followers?following_id=eq.'+uid+'&select=id');var fanN=await api('/rest/v1/followers?follower_id=eq.'+uid+'&select=id');var pct=Math.min(100,Math.round((u.exp-expLv(u.level))/(expLv(u.level+1)-expLv(u.level))*100));var editBtn=isMe2?'<div style="margin-top:8px"><span style="background:#F0E6FF;color:#7B68EE;padding:5px 20px;border-radius:14px;font-size:12px;cursor:pointer" onclick="goPage(\'editPage\')">✏️ 编辑资料</span></div>':'';var folBtn=isMe2?'':'<span class="follow-btn '+(fol&&fol.length?'':'on')+'" style="background:'+(fol&&fol.length?'#eee':'linear-gradient(135deg,#7B68EE,#6A5ACD)')+';color:'+(fol&&fol.length?'#555':'#fff')+'" onclick="'+(fol&&fol.length?'unfollowUser(\''+uid+'\')':'followUser(\''+uid+'\')')+'">'+(fol&&fol.length?'已关注':'＋关注')+'</span>';$('userBox').innerHTML='<div class="ubg">'+(u.bg_image?'<img src="'+esc(u.bg_image)+'" onerror="this.parentNode.style.background=\'linear-gradient(135deg,#7B68EE,#6A5ACD)\'">':'')+'<div class="ubg-avatar">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'">':esc((u.nickname||'友')[0]))+'</div></div><div class="uinfo"><div class="uname">'+esc(u.nickname)+(u.role==='admin'?'<span class="utag">管理员</span>':'')+'</div>'+(me&&me.role==='admin'&&!isMe2?'<div style="font-size:12px;color:#999;margin-top:3px">QQ：'+esc(u.qq||'-')+'</div>':'')+'<div class="pt-exp"><i style="width:'+Math.max(4,pct)+'%"></i></div><div class="pt-exp-t">Lv'+u.level+'·经验'+u.exp+'/'+expLv(u.level+1)+'</div><div style="font-size:12px;color:#666;margin-top:6px">'+esc(u.bio||'这个人很懒')+'</div><div class="stat-card" style="margin-top:8px"><div><div class="stat-num" style="color:#ff9500">🪙'+u.coins+'</div><div class="stat-label">硬币</div></div><div><div class="stat-num" style="color:#7B68EE">'+(folN?folN.length:0)+'</div><div class="stat-label">关注</div></div><div><div class="stat-num" style="color:#6A5ACD">'+(fanN?fanN.length:0)+'</div><div class="stat-label">粉丝</div></div></div>'+editBtn+folBtn+'</div>';loadUserPosts('posts');goPage('userPage');}catch(e){toast('加载失败');}}
async function loadUserPosts(tab){$('ut1').classList.toggle('on',tab==='posts');$('ut2').classList.toggle('on',tab==='comments');try{if(tab==='posts'){var d=await api('/rest/v1/posts?select=*,author_id(nickname,level)&author_id=eq.'+curUser+'&status=eq.published&order=created_at.desc&limit=50');renderCards(d,$('userList'),'TA还没有发过帖子');}else{var d2=await api('/rest/v1/comments?select=*,author_id(nickname,level)&author_id=eq.'+curUser+'&status=eq.published&order=created_at.desc&limit=50');$('userList').innerHTML=(!d2||!d2.length)?'<div class="empty">TA还没有评论</div>':d2.map(function(c){return '<div class="comment-box"><div class="cb-text">'+esc(c.content)+'</div><div class="cb-time">'+fmt(c.created_at)+'</div></div>';}).join('');}}catch(e){$('userList').innerHTML='<div class="empty">加载失败</div>';}}
async function followUser(uid){if(!me){toast('请先登录');needLogin();return;}try{var r=await dbR('follow_user',{p_following_id:uid});toast(r==='OK'?'✅已关注':r);openUser(uid);}catch(e){toast('失败');}}
async function unfollowUser(uid){try{await dbR('unfollow_user',{p_following_id:uid});toast('已取消关注');openUser(uid);}catch(e){toast('失败');}}

var GRID=[['📅','签到','signPage'],['⭐','收藏','favPage'],['🏆','排行','rankPage'],['🎟️','邀请','invitePage'],['💬','交流群','groupPage'],['🛡️','后台','adminPage'],['🍅','番茄','pomoPage'],['🎨','美化','editPage'],['🚪','退出','logout']];
async function loadMe(){if(!me)return;var u=me;var folN=await api('/rest/v1/followers?following_id=eq.'+u.id+'&select=id').catch(function(){return[];});var fanN=await api('/rest/v1/followers?follower_id=eq.'+u.id+'&select=id').catch(function(){return[];});var pct=Math.min(100,Math.round((u.exp-expLv(u.level))/(expLv(u.level+1)-expLv(u.level))*100));$('meProfile').innerHTML='<div class="me-card" onclick="openUser(\''+u.id+'\')"><div class="me-avatar">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'">':esc((u.nickname||'友')[0]))+'</div><div style="flex:1"><div class="me-name">'+esc(u.nickname)+(u.role==='admin'?'<span class="utag">管理员</span>':'')+'<span style="font-size:10px;color:#6A5ACD;margin-left:6px">💯'+u.credit+'</span></div><div class="me-exp"><i style="width:'+Math.max(4,pct)+'%"></i></div><div class="me-exp-t">Lv'+u.level+'·'+u.exp+'/'+expLv(u.level+1)+'</div></div><div class="me-arrow">›</div></div>';$('meGrid').innerHTML=GRID.filter(function(g){return g[2]!=='adminPage'||(me&&me.role==='admin');}).map(function(g){return g[2]==='logout'?'<div class="grid-item" onclick="logout()"><div class="gi">'+g[0]+'</div><div class="gt">'+g[1]+'</div></div>':'<div class="grid-item" onclick="goPage(\''+g[2]+'\')"><div class="gi">'+g[0]+'</div><div class="gt">'+g[1]+'</div></div>';}).join('');$('topAvatar').textContent=u.nickname?u.nickname[0]:'友';}
function loadGroup(){$('groupBox').innerHTML='<div class="dc-card"><div class="dc-h">💬 加入花学社交流群</div>'+GROUP_LINKS.map(function(g){return '<div class="his-card" onclick="location.href=\''+g.u+'\'"><span style="flex:1;font-size:14px">'+g.n+'</span><span style="color:#7B68EE">›</span></div>';}).join('')+'</div><div class="tip" style="text-align:center">点击加入</div>';}
async function loadHistory(){try{var h=await api('/rest/v1/history?select=post_id&user_id=eq.'+me.id+'&order=viewed_at.desc&limit=20');if(!h||!h.length){$('historyList').innerHTML='<div class="empty" style="padding:6px 0">暂无记录</div>';return;}var ids=h.map(function(x){return x.post_id;});var posts=await api('/rest/v1/posts?select=id,title&id=in.('+ids.join(',')+')&status=eq.published');$('historyList').innerHTML=posts&&posts.length?posts.map(function(p){return '<div class="his-card" onclick="openPost('+p.id+')"><span style="flex:1;font-size:13px">'+esc(p.title)+'</span><span style="font-size:10px;color:#bbb">›</span></div>';}).join(''):'<div class="empty" style="padding:6px 0">暂无</div>';}catch(e){$('historyList').innerHTML='<div class="empty" style="padding:6px 0">暂无</div>';}}

function initEdit(){var bgs=[['默认',''],['浅蓝','linear-gradient(180deg,#e8f1ff,#F0E6FF)'],['浅绿','linear-gradient(180deg,#e6f7ec,#F0E6FF)'],['浅紫','linear-gradient(180deg,#efe9ff,#F0E6FF)'],['暖黄','linear-gradient(180deg,#fff7e0,#F0E6FF)']];var cur=localStorage.getItem('hxs_bg')||'';$('bgChips').innerHTML=bgs.map(function(b,i){return '<div class="chip '+(cur===b[1]?'on':'')+'" onclick="pickBg(this,'+i+')">'+b[0]+'</div>';}).join('');$('eBio').value=me.bio||'';$('editErr').textContent='';$('avPreview').innerHTML='';$('bgPreview').innerHTML='';}
function pickBg(el,i){var bgs=[[''],['linear-gradient(180deg,#e8f1ff,#F0E6FF)'],['linear-gradient(180deg,#e6f7ec,#F0E6FF)'],['linear-gradient(180deg,#efe9ff,#F0E6FF)'],['linear-gradient(180deg,#fff7e0,#F0E6FF)']];localStorage.setItem('hxs_bg',bgs[i]);document.querySelectorAll('#bgChips .chip').forEach(function(x){x.classList.remove('on');});el.classList.add('on');applyBg();toast('🎨已应用');}
async function saveProfile(){if(!me){toast('请先登录');needLogin();return;}var bio=$('eBio').value.trim();try{var avatar_url=me.avatar_url||'';var bg_image=me.bg_image||'';var fa=$('eAvatar')._selected;if(fa)avatar_url=await uploadImg(fa);var fb=$('eBg')._selected;if(fb)bg_image=await uploadImg(fb);await dbU('profiles','id=eq.'+me.id,{bio:bio,avatar_url:avatar_url,bg_image:bg_image});me.bio=bio;me.avatar_url=avatar_url;me.bg_image=bg_image;toast('✅已保存');loadMe();goPage('mePage');}catch(e){$('editErr').textContent='保存失败：'+e.message;}}

async function loadInvite(){if(!me)return;$('inviteBox').innerHTML='<div class="uinfo"><div style="font-size:14px;color:#999">我的邀请码</div><div style="font-size:30px;font-weight:800;color:#7B68EE;margin:6px 0;letter-spacing:3px">'+esc(me.invite_code||'---')+'</div><button class="btn" style="max-width:200px" onclick="copyInvite()">📋复制邀请码</button><div class="tip" style="text-align:center">好友注册时填写你的邀请码<br>每成功邀请1人+25硬币</div></div>';}
function copyInvite(){if(navigator.clipboard)navigator.clipboard.writeText(me.invite_code||'').then(function(){toast('✅已复制');}).catch(function(){toast('复制失败');});else toast('邀请码：'+(me.invite_code||''));}
async function loadInfoCount(){if(!me)return;try{var r=await api('/rest/v1/notifications?user_id=eq.'+me.id+'&is_read=eq.false&select=id');if(r&&r.length){$('topBadge').textContent=r.length;$('topBadge').style.display='inline';}else{$('topBadge').style.display='none';}}catch(e){}}
async function loadInfo(){if(!me){$('infoList').innerHTML='<div class="empty">请先登录</div>';return;}try{var d=await api('/rest/v1/notifications?user_id=eq.'+me.id+'&order=created_at.desc&limit=50');$('infoList').innerHTML=(!d||!d.length)?'<div class="empty">还没有消息</div>':d.map(function(n){return '<div class="notif-item '+(n.is_read?'':'unread')+'"><span style="font-size:18px">'+(n.type==='like'?'👍':n.type==='comment'?'💬':n.type==='coin'?'🪙':n.type==='follow'?'👥':'⚠️')+'</span><div style="flex:1"><div style="font-size:13px">'+esc(n.content)+'</div><div style="font-size:11px;color:#bbb;margin-top:2px">'+fmt(n.created_at)+'</div></div></div>';}).join('');await dbU('notifications','user_id=eq.'+me.id,{is_read:true});loadInfoCount();}catch(e){$('infoList').innerHTML='<div class="empty">加载失败</div>';}}

async function loadSign(){try{var d=await api('/rest/v1/checkins?user_id=eq.'+me.id+'&order=checkin_date.desc&limit=7');var today=new Date().toISOString().slice(0,10);var done=d&&d[0]&&d[0].checkin_date===today;var streak=d&&d[0]?d[0].streak:0;var hist='';if(d)hist=d.map(function(c){return '<span style="margin:0 3px;font-size:18px">'+(c.checkin_date===today?'✅':'📅')+'</span>';}).join('');$('signBox').innerHTML='<div style="font-size:18px;font-weight:700;margin-bottom:4px">连续签到：<span style="color:#ff9500">'+streak+'天</span></div><div style="margin-bottom:8px">'+hist+'</div><div class="tip" style="margin-bottom:14px">连续7天+1经验+2硬币，30天+3经验+5硬币</div>'+(done?'<div style="color:#999;padding:14px 0">今天已经签过啦</div>':'<button class="btn" style="max-width:220px" onclick="doCheckin()">📅立即签到</button>');}catch(e){$('signBox').innerHTML='<div class="empty">加载失败</div>';}}
async function doCheckin(){try{var r=await dbI('checkins',{user_id:me.id});toast('✅签到成功！连续'+r[0].streak+'天，+'+r[0].reward+'硬币');me=await fetchMe();loadSign();}catch(e){toast(e.message&&e.message.indexOf('23505')>-1?'今天已经签过啦':'签到失败');}}

async function loadRank(type){rank=type;$('tabGood').classList.toggle('on',type==='good');$('tabLike').classList.toggle('on',type==='like');$('tabLevel').classList.toggle('on',type==='level');$('rankList').innerHTML='<div class="empty">加载中...</div>';try{if(type==='good'){var d=await api('/rest/v1/posts?select=*,author_id(nickname,level)&status=eq.published&order=good_count.desc&limit=20');$('rankList').innerHTML=(!d||!d.length)?'<div class="empty">暂无</div>':d.map(function(p,i){return '<div class="rank-item"><div class="rank-no '+(i<3?'top'+(i+1):'')+'">'+(i+1)+'</div><div style="flex:1;margin-left:6px"><div style="font-size:13px">'+esc(p.title)+'</div><div style="font-size:11px;color:#999">👤'+esc(p.author_id?p.author_id.nickname||'':'')+'</div></div><div style="font-size:13px;color:#ff9500;font-weight:600">❤️'+p.good_count+'</div></div>';}).join('');}else if(type==='like'){var d2=await api('/rest/v1/posts?select=*,author_id(nickname,level)&status=eq.published&order=like_count.desc&limit=20');$('rankList').innerHTML=(!d2||!d2.length)?'<div class="empty">暂无</div>':d2.map(function(p,i){return '<div class="rank-item"><div class="rank-no '+(i<3?'top'+(i+1):'')+'">'+(i+1)+'</div><div style="flex:1;margin-left:6px"><div style="font-size:13px">'+esc(p.title)+'</div><div style="font-size:11px;color:#999">👤'+esc(p.author_id?p.author_id.nickname||'':'')+'</div></div><div style="font-size:13px;color:#7B68EE;font-weight:600">👍'+p.like_count+'</div></div>';}).join('');}else{var d3=await api('/rest/v1/profiles?select=*&order=exp.desc&limit=20');$('rankList').innerHTML=(!d3||!d3.length)?'<div class="empty">暂无</div>':d3.map(function(u,i){return '<div class="rank-item"><div class="rank-no '+(i<3?'top'+(i+1):'')+'">'+(i+1)+'</div><div style="flex:1;margin-left:6px;font-size:13px">'+esc(u.nickname)+(u.role==='admin'?'<span class="lv" style="background:#e5484d">管理</span>':'')+'</div><div style="font-size:12px;color:#7B68EE;font-weight:600"><span class="lv" style="background:#7B68EE">Lv'+u.level+'</span>⚡'+u.exp+'</div></div>';}).join('');}}catch(e){$('rankList').innerHTML='<div class="empty">加载失败</div>';}}

function pomoStart(){var b=$('pomoBtn');if(pomoT){clearInterval(pomoT);pomoT=null;b.textContent='继续';$('pomoState').textContent='已暂停';return;}var h=parseInt($('pomoH').value)||0,m=parseInt($('pomoM').value)||0,s=parseInt($('pomoS').value)||0;pomoL=h*3600+m*60+s;if(pomoL<=0){toast('请设置时间');return;}b.textContent='暂停';$('pomoState').textContent='专注中…';pomoT=setInterval(function(){pomoL--;if(pomoL<=0){clearInterval(pomoT);pomoT=null;b.textContent='开始';$('pomoState').textContent='🍅完成！';toast('🍅番茄完成！');return;}pomoRender();},1000);}
function pomoReset(){if(pomoT){clearInterval(pomoT);pomoT=null;}$('pomoBtn').textContent='开始';$('pomoState').textContent='自定义时/分/秒';pomoL=1500;pomoRender();}
function pomoRender(){var h=String(Math.floor(pomoL/3600)).padStart(2,'0'),m=String(Math.floor(pomoL%3600/60)).padStart(2,'0'),s=String(pomoL%60).padStart(2,'0');$('pomoTime').textContent=(h>0?h+':':'')+m+':'+s;}
function renderCourses(){$('courseList').innerHTML=COURSES.map(function(c,i){return '<div class="his-card" onclick="location.href=\''+c.u+'\'"><span style="flex:1;font-size:13px">'+(c.p==='bili'?'🔵':'🔴')+c.t+'</span><span style="font-size:11px;color:'+(c.p==='bili'?'#fb7299':'#161823')+'">'+(c.p==='bili'?'B站':'抖音')+'</span><span style="color:#6A5ACD;font-size:12px;cursor:pointer;margin-left:6px" onclick="event.stopPropagation();favCourse('+i+')">⭐</span></div>';}).join('');}
async function favCourse(idx){if(!me){toast('请先登录');needLogin();return;}try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.course&target_id=eq.'+idx+'&limit=1');if(r&&r.length){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.course&target_id=eq.'+idx);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:'course',target_id:idx});toast('⭐已收藏');}}catch(e){toast('失败');}}

function showAt(){var sel=$('atSel');if(!me){sel.style.display='none';return;}try{var admins=await api('/rest/v1/profiles?select=nickname,id&role=eq.admin&limit=50');var follows=await api('/rest/v1/followers?select=following_id&follower_id=eq.'+me.id+'&limit=200');var list=[];if(admins)list=list.concat(admins.filter(function(a){return a.id!==me.id;}));if(follows&&follows.length){var ids=follows.map(function(f){return f.following_id;});var fs=await api('/rest/v1/profiles?select=nickname,id&id=in.('+ids.join(',')+')');if(fs)list=list.concat(fs.filter(function(f){return f.id!==me.id;}));}list=list.filter(function(v,i,a){return a.findIndex(function(x){return x.id===v.id;})===i;});sel.innerHTML=list.length?list.map(function(u){return '<div class="at-i" onclick="insertAt(\''+esc(u.nickname)+'\')">@'+esc(u.nickname)+'</div>';}).join(''):'<div class="at-i">可@管理员及关注的人</div>';sel.style.display='block';}catch(e){sel.style.display='none';}}
function insertAt(name){var inp=$('pContent')||$('cmInput');if(inp)inp.value+='@'+name+' ';$('atSel').style.display='none';if(inp.id==='cmInput')inp.focus();}

async function loadRes(type){resType=type;$('resTab1').classList.toggle('on',type==='video');$('resTab2').classList.toggle('on',type==='app');$('resList').innerHTML='<div class="empty">加载中...</div>';try{var d=await api('/rest/v1/resources?select=*&type=eq.'+type+'&order=created_at.desc');if(!d||!d.length){$('resList').innerHTML='<div class="empty">暂无内容</div>';return;}var isAdmin=me&&me.role==='admin';if(type==='video'){$('resList').innerHTML=d.map(function(r){return '<div class="video-card"><div class="video-cover" onclick="location.href=\''+esc(r.link)+'\'">▶️</div><div class="video-info"><div class="vt">'+esc(r.title)+'<span class="lv" style="margin-left:4px;background:#7B68EE">'+(r.pan_type||'外站')+'</span></div><div class="vs">'+esc(r.description||'')+'·点击观看</div>'+(isAdmin?'<div style="margin-top:4px"><span style="color:#e5484d;font-size:11px;cursor:pointer" onclick="delRes('+r.id+')">🗑删除</span></div>':'')+'</div></div>';}).join('');}else{$('resList').innerHTML=d.map(function(r){return '<div class="app-card" onclick="openAppDetail('+r.id+')"><div class="ac-top"><div class="ac-icon" style="background:#eee;text-align:center;line-height:48px;font-size:22px">'+(r.icon?'<img src="'+esc(r.icon)+'" class="ac-icon">':'📱')+'</div><div><div class="ac-title">'+esc(r.title)+'<span class="lv" style="margin-left:4px;background:#ff9500">'+(r.size_mb||'')+'</span></div><div class="ac-sub">'+esc(r.description||'')+'·📥'+(r.downloads||0)+'次</div>'+(isAdmin?'<div style="margin-top:4px"><span style="color:#e5484d;font-size:11px;cursor:pointer" onclick="event.stopPropagation();delRes('+r.id+')">🗑删除</span></div>':'')+'</div></div></div>';}).join('');}}catch(e){$('resList').innerHTML='<div class="empty">加载失败</div>';}}
async function delRes(rid){if(!confirm('确定删除？'))return;try{await dbD('resources','id=eq.'+rid);toast('已删除');loadRes(resType);}catch(e){toast('失败');}}
function initResPost(){$('resTypeChips').innerHTML=[['video','🎬视频'],['app','📱应用']].map(function(x){return '<div class="chip '+(x[0]===resType?'on':'')+'" onclick="pickResType(this,\''+x[0]+'\')">'+x[1]+'</div>';}).join('');$('resErr').textContent='';}
function pickResType(el,k){resType=k;document.querySelectorAll('#resTypeChips .chip').forEach(function(x){x.classList.remove('on');});el.classList.add('on');}
async function submitRes(){if(!me||me.role!=='admin'){toast('仅管理员');return;}var title=$('resTitle').value.trim(),desc=$('resDesc').value.trim(),link=$('resLink').value.trim(),size=$('resSize').value.trim();if(!title||!link){$('resErr').textContent='请填标题和链接';return;}var icon='';var f=$('resImg')._selected;try{if(f)icon=await uploadImg(f);await dbI('resources',{title:title,description:desc,type:resType,link:link,icon:icon,size_mb:size||null,created_by:me.id});toast('✅已发布');$('resTitle').value='';$('resDesc').value='';$('resLink').value='';$('resSize').value='';$('resImg').value='';$('resImg')._selected=null;$('resImgPreview').innerHTML='';goPage('resourcePage');}catch(e){$('resErr').textContent='失败：'+e.message;}}
async function openAppDetail(id){try{var r=await api('/rest/v1/resources?id=eq.'+id);var d=r&&r[0];if(!d)return;var fav=me?await isFav('app',d.id):false;$('appDetailBox').innerHTML='<div style="background:#fff;border-radius:12px;padding:16px;text-align:center;margin-bottom:10px">'+(d.icon?'<img src="'+esc(d.icon)+'" style="width:72px;height:72px;border-radius:14px;object-fit:cover;margin-bottom:8px">':'<div style="width:72px;height:72px;border-radius:14px;background:#eee;line-height:72px;margin:0 auto 8px;font-size:28px">📱</div>')+'<div style="font-size:17px;font-weight:700">'+esc(d.title)+'</div></div><div style="background:#fff;border-radius:12px;padding:14px;font-size:13px;line-height:1.7;color:#444;margin-bottom:10px">'+esc(d.description||'暂无介绍')+'</div><div class="stat-card"><div><div class="stat-num">'+(d.downloads||0)+'</div><div class="stat-label">下载</div></div><div><div class="stat-num">'+(d.size_mb||'--')+'</div><div class="stat-label">大小</div></div></div><div class="detail-actions"><button class="action-btn '+(fav?'on':'')+'" style="border-color:#7B68EE;color:#7B68EE" onclick="favRes(\'app\','+d.id+')">⭐'+(fav?'已收藏':'收藏')+'</button><button class="action-btn" style="border-color:#ff9500;color:#ff9500" onclick="location.href=\''+esc(d.link)+'\'">🔗下载</button>'+(me&&me.role==='admin'?'<button class="action-btn" style="color:#e5484d" onclick="delRes('+d.id+')">🗑删除</button>':'')+'</div>';goPage('appDetailPage');}catch(e){toast('加载失败');}}
async function favRes(type,rid){if(!me){toast('请先登录');needLogin();return;}try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.'+type+'&target_id=eq.'+rid+'&limit=1');if(r&&r.length){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.'+type+'&target_id=eq.'+rid);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:type,target_id:rid});toast('⭐已收藏');}loadRes(resType);}catch(e){toast('失败');}}

async function loadAdmin(tab){$('aTab1').classList.toggle('on',tab==='reports');$('aTab2').classList.toggle('on',tab==='punish');$('aTab3').classList.toggle('on',tab==='posts');if(tab==='posts'){try{var d=await api('/rest/v1/posts?select=*,author_id(nickname,level)&status=eq.published&order=created_at.desc&limit=100');$('adminBox').innerHTML='<div class="tip" style="margin-bottom:8px">共'+d.length+'个帖子 · 勾选后批量删除</div><div style="display:flex;gap:8px;margin-bottom:8px"><button class="btn" onclick="document.querySelectorAll(\'.ap\').forEach(function(x){x.checked=true;})">全选</button><button class="btn" style="background:#e5484d" onclick="delSelPosts()">删除选中</button></div>'+d.map(function(p){return '<label style="display:flex;align-items:center;padding:8px 0;border-bottom:1px solid #f4f4f4;font-size:13px"><input type="checkbox" class="ap" value="'+p.id+'" style="margin-right:8px">'+esc(p.title)+'<span style="margin-left:auto;color:#999;font-size:11px">👤'+esc(p.author_id?p.author_id.nickname||'':'')+'</span></label>';}).join('');}catch(e){$('adminBox').innerHTML='<div class="empty">加载失败</div>';}}else if(tab==='reports'){try{var d2=await api('/rest/v1/reports?status=eq.pending&order=created_at.desc');if(!d2||!d2.length){$('adminBox').innerHTML='<div class="empty">没有待处理举报🎉</div>';return;}var h='<div class="tip" style="margin-bottom:8px">共'+d2.length+'条</div>';for(var i=0;i<d2.length;i++){var r=d2[i],target='',content='';try{if(r.target_type==='post'){var p=await api('/rest/v1/posts?id=eq.'+r.target_id);if(p&&p[0]){target='帖子：'+p[0].title;content=p[0].content;}}else{var c=await api('/rest/v1/comments?id=eq.'+r.target_id);if(c&&c[0]){target='评论#'+r.target_id;content=c[0].content;}}}catch(e){}h+='<div class="comment-box"><div style="font-size:13px;font-weight:600">🚩'+esc(r.reason)+'</div><div style="font-size:11px;color:#999;margin:4px 0">'+esc(target)+'</div><div style="font-size:12px;color:#555;background:#f7f8fa;border-radius:8px;padding:8px;margin:8px 0">'+esc(content)+'</div><div style="display:flex;gap:8px"><button class="btn" style="background:#999;flex:1" onclick="handleReport('+r.id+',\'ignore\')">忽略</button><button class="btn" style="flex:1" onclick="handleReport('+r.id+',\'delete\')">删内容</button><button class="btn" style="background:#e5484d;flex:1" onclick="handleReport('+r.id+',\'punish\')">删+扣分</button></div></div>';}$('adminBox').innerHTML=h;}catch(e){$('adminBox').innerHTML='<div class="empty">加载失败</div>';}}else{$('adminBox').innerHTML='<div class="tip" style="margin-bottom:8px">按QQ号查找用户</div><input id="punishQQ" class="inp" placeholder="输入QQ号"><button class="btn" onclick="findUser()">查找</button><div id="userInfo" style="margin-top:10px"></div>';}}
async function delSelPosts(){var sel=[].slice.call(document.querySelectorAll('.ap:checked')).map(function(x){return x.value;});if(!sel.length){toast('请先选择');return;}if(!confirm('确定删除'+sel.length+'个帖子？'))return;for(var i=0;i<sel.length;i++){try{await dbR('delete_post',{pid:sel[i]});}catch(e){}}toast('✅已删除');loadAdmin('posts');}
async function findUser(){var kw=$('punishQQ').value.trim();try{var d=await api('/rest/v1/profiles?select=*&qq=eq.'+kw+'&limit=1');if(!d||!d.length){$('userInfo').innerHTML='<div class="empty">没找到</div>';return;}var u=d[0];$('userInfo').innerHTML='<div class="comment-box"><div style="font-weight:600">👤'+esc(u.nickname)+'(QQ:'+esc(u.qq||'-')+')</div><div style="font-size:12px;color:#555;background:#f7f8fa;border-radius:8px;padding:8px;margin:6px 0">Lv'+u.level+'·🪙'+u.coins+'·💯'+u.credit+(u.is_banned?'·⛔已封号':'')+'</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" style="background:#e5484d" onclick="punish(\''+u.id+'\',\'credit\',10)">扣10分</button><button class="btn" style="background:#e5484d" onclick="punish(\''+u.id+'\',\'credit\',50)">扣50分</button><button class="btn" onclick="punish(\''+u.id+'\',\'mute\',1)">禁1天</button><button class="btn" style="background:#e5484d" onclick="punish(\''+u.id+'\',\'ban\',0)">封号</button><button class="btn" style="background:#e5484d" onclick="punish(\''+u.id+'\',\'device_ban\',0)">封设备</button><button class="btn" style="background:#999" onclick="punish(\''+u.id+'\',\'unban\',0)">解封</button></div></div>';}catch(e){$('userInfo').innerHTML='<div class="empty">查询失败</div>';}}
async function punish(uid,action,amount){try{var r=await dbR('admin_punish',{p_user_id:uid,p_action:action,p_amount:amount,p_detail:action==='mute'?'禁言':(action==='ban'?'封号':(action==='device_ban'?'封设备':'扣分'))});toast(r==='OK'?'✅已执行':('⚠️'+r));setTimeout(function(){findUser();},600);}catch(e){toast('失败');}}
async function handleReport(rid,act){try{if(act==='ignore'){await dbU('reports','id=eq.'+rid,{status:'ignored'});toast('已忽略');}else{var r=await api('/rest/v1/reports?id=eq.'+rid);var rep=r&&r[0];if(rep){if(rep.target_type==='post'){var p=await api('/rest/v1/posts?id=eq.'+rep.target_id);if(p&&p[0]){if(act==='punish')await dbR('admin_punish',{p_user_id:p[0].author_id,p_action:'credit',p_amount:10,p_detail:'举报成立'});await dbR('delete_post',{pid:rep.target_id});}}else{await dbR('delete_comment',{cid:rep.target_id});}await dbU('reports','id=eq.'+rid,{status:'handled'});if(rep.reporter_id)dbR('reward_report',{p_reporter_id:rep.reporter_id}).catch(function(){});toast('✅已处理');}}loadAdmin('reports');}catch(e){toast('处理失败');}}

if(curUser2())showMain();else goPage('loginPage');