// ===== 花学社 v18 =====
var BOARDS=[{key:'jinghua',name:'✨精选'},{key:'remen',name:'🔥热门'},{key:'note',name:'📒笔记'},{key:'jiqiao',name:'💡技巧'},{key:'tiwen',name:'🙋提问'},{key:'haowu',name:'🛍️学习好物推荐'},{key:'suibi',name:'✍️随笔'},{key:'feihualing',name:'🌸飞花令'},{key:'ruozhiba',name:'🤪弱智吧'},{key:'chigua',name:'🍉吃瓜灌水'},{key:'meishi',name:'🍜美食'}];
var POST_BOARDS=BOARDS.filter(function(b){return b.key!=='jinghua'&&b.key!=='remen';});
var ADS=[{t:'📶广电正规卡',s:'39元/月·60G·发全国',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12539&agent_id=2783784'},{t:'📶联通碧海卡',s:'29元/月·110G+100分钟·仅发海南',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12543&agent_id=2783784'},{t:'📶联通大禹卡',s:'39元/月·60G+200分钟·只发重庆',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12542&agent_id=2783784'},{t:'📶广电奔马卡',s:'39元/月·60G·只发陕西',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12540&agent_id=2783784'},{t:'📶联通川速卡',s:'39元/月·60G+50分钟·只发四川',u:'https://m20260808.yapingkeji.com/pages/detail/index?goods_id=12541&agent_id=2783784'}];
var COURSES=[{t:'高中数学·基础精讲',s:'B站',p:'bili',u:'https://space.bilibili.com'},{t:'英语语法·从零到通',s:'B站',p:'bili',u:'https://www.bilibili.com'},{t:'物理思维·解题技巧',s:'抖音',p:'douyin',u:'https://www.douyin.com'},{t:'学习方法·高效记忆',s:'抖音',p:'douyin',u:'https://www.douyin.com'}];
var TIANAPI_KEY='d6dd74802a387df1bb11649ae7a6afcd';
var RULES='《花学社社区总版规》v2.0\n一、总则：花学社是面向大众学习者的学习交流社区，提倡真诚分享、友善互助、专注学习。注册即视为同意本版规。\n二、账号：一人一号严禁小号；Lv.1新用户24h内仅可浏览。\n三、发帖：内容与板块相符、标题简明、主题帖最低2汉字；禁止水帖/刷屏/恶意填分类。\n四、红线：1.链接/二维码：首次拦截不扣分；24h内累计3次→扣30分+禁言7天；5次以上→永久封号+封设备。2.黄赌毒→清分封号封设备。3.辱骂→首次扣10+禁1天再犯扣20+禁3天。4.造谣→同辱骂。5.政治→扣50封号。6.广告引流→扣10~50+禁言/封号。7.侵犯隐私→扣20+禁3天。8.脚本刷分→清分封号封设备。9.挂机→弹验证码/扣20分。10.刷屏→扣20+禁3天。11.无意义评论24h超10条→扣20+禁3天。12.频繁删帖≥5次→禁1天。13.恶意举报→按引战处理。\n五、奖励：签到+2经验+1硬币（连续7天+1/+2，30天+3/+5）；发帖+1经验+2硬币（日限1）；评论+1经验+1硬币（日限1）；被好评+2经验+2信誉分；解题+5经验+5信誉分（日限2）；邀请+25硬币（月限5）；举报成立+3经验+3信誉分+10硬币；阅读简报+1经验+1硬币（日限1）。\n六、等级：0/30/80/160/300/500/800/1200/1800/2500经验。\n七、硬币：打赏1~1000枚/次。\n八、信誉分(满分100)：80~100正常；60~80减半；40~60禁3天+人工审核；20~40禁7天+仅浏览；0~20永久禁言。\n九、好评：普通用户每3天一次（资格不累积）；管理员无限制。\n十、评论删除扣回奖励+50%罚金。\n十一、最终解释权归管理员。';
var WELCOME='📜 红线：链接/二维码累计3次→扣30分+禁7天，5次→封号封设备；黄赌毒→清分封号；辱骂→首次扣10+禁1天再犯扣20+禁3天；政治→扣50封号。\n🪙 每日：签到+1硬币、发帖+2、评论+1、阅读简报+1；日限1次。\n⚡ 每日经验上限4点。\n💯 信誉分满分100，低于80权限受限。\n👍 好评：普通用户每3天一次，管理员无限制。';
function $(id){return document.getElementById(id);}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function fmt(t){if(!t)return'';var d=new Date(t),n=new Date(),p=function(x){return String(x).padStart(2,'0');};return d.toDateString()===n.toDateString()?p(d.getHours())+':'+p(d.getMinutes()):(d.getMonth()+1)+'月'+d.getDate()+'日';}
function fmtFull(t){if(!t)return'';var d=new Date(t),p=function(x){return String(x).padStart(2,'0');};return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate());}
function toast(m){var t=$('toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(function(){t.classList.remove('show');},2200);}
function did(){var d=localStorage.getItem('did');if(!d){d='dev-'+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem('did',d);}return d;}
function authH(){var h={'apikey':SUPABASE_ANON_KEY,'Content-Type':'application/json'};var t=localStorage.getItem('sb_token');if(t)h['Authorization']='Bearer '+t;return h;}
async function refreshT(){var rt=localStorage.getItem('sb_refresh');if(!rt)throw new Error('no rt');var r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'apikey':SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:rt})});var j=await r.json();if(j&&j.access_token){localStorage.setItem('sb_token',j.access_token);localStorage.setItem('sb_refresh',j.refresh_token);return j.access_token;}throw new Error('refresh failed');}
async function api(path,opt){opt=opt||{};var h=authH();if(opt.headers)for(var k in opt.headers)h[k]=opt.headers[k];var res=await fetch(SUPABASE_URL+path,{...opt,headers:h});if(res.status===401){try{await refreshT();var h2=authH();if(opt.headers)for(var k2 in opt.headers)h2[k2]=opt.headers[k2];res=await fetch(SUPABASE_URL+path,{...opt,headers:h2});}catch(e){logout();throw new Error('登录已过期');}}if(!res.ok){var m='HTTP '+res.status;try{var j=await res.json();m=j.msg||j.message||j.hint||m;}catch(e){}throw new Error(m);}var txt=await res.text();if(!txt)return null;try{return JSON.parse(txt);}catch(e){return txt;}}
function qs(o){var r=[];for(var k in o)r.push(encodeURIComponent(k)+'='+encodeURIComponent(o[k]));return r.join('&');}
function dbI(t,b){return api('/rest/v1/'+t,{method:'POST',headers:{'Prefer':'return=representation'},body:JSON.stringify(b)});}
function dbU(t,f,b){return api('/rest/v1/'+t+'?'+f,{method:'PATCH',headers:{'Prefer':'return=representation'},body:JSON.stringify(b)});}
function dbD(t,f){return api('/rest/v1/'+t+'?'+f,{method:'DELETE'});}
function dbR(f,a){return api('/rest/v1/rpc/'+f,{method:'POST',body:JSON.stringify(a||{})});}
function expLv(l){var t={1:0,2:30,3:80,4:160,5:300,6:500,7:800,8:1200,9:1800,10:2500};return t[l]||2500;}
function applyBg(){try{var b=localStorage.getItem('hxs_bg')||'';document.body.style.background=b||'#F0E6FF';document.body.style.backgroundImage=localStorage.getItem('hxs_bgimg')||'none';}catch(e){}}
var curBoard='jinghua',curPost=null,me=null,sort='new',tipAmt=1,rank='good',resType='video',favType='app',searching=false,isReg2=false,captchaCode='',adIdx=0,adT=null,cmImg=null,curUser=null,replyTo=null,afkT=null,afkC='',spT=null,pomoT=null,pomoL=0,ctxTimer=null,currentCmId=null,infoType='interact',friendType='following';
try{applyBg();}catch(e){}

function drawCaptcha(){captchaCode='';var s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(var i=0;i<4;i++)captchaCode+=s[Math.floor(Math.random()*s.length)];var c=$('captchaCanvas');if(!c)return;var x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#f0edf7';x.fillRect(0,0,c.width,c.height);for(var i=0;i<6;i++){x.strokeStyle='hsl('+Math.random()*360+',50%,70%)';x.lineWidth=1;x.beginPath();x.moveTo(Math.random()*c.width,Math.random()*c.height);x.lineTo(Math.random()*c.width,Math.random()*c.height);x.stroke();}x.textBaseline='middle';for(var i=0;i<captchaCode.length;i++){x.fillStyle='hsl('+(Math.random()*60+220)+',70%,35%)';x.font='bold 26px "Courier New",monospace';x.fillText(captchaCode[i],12+i*24+Math.random()*6,22+Math.random()*6);}}
function toggleReg2(){isReg2=!isReg2;var re=$('regExtra'),tb=$('toggleBtn'),bt=$('btnText');if(re)re.classList.toggle('open',isReg2);if(tb)tb.textContent=isReg2?'已有账号？去登录':'没有账号？去注册';if(bt)bt.textContent=isReg2?'注 册':'登 录';var le=$('loginErr');if(le)le.textContent='';drawCaptcha();}
function fakeEmail(qq){return'qq'+qq.trim()+'@qq.local';}
async function handleLogin(){var errEl=$('loginErr'),qqEl=$('loginQQ'),passEl=$('loginPass'),btn=$('mainBtn'),bt=$('btnText');if(!qqEl||!passEl){toast('页面加载异常');return;}var qq=qqEl.value.trim(),pass=passEl.value;if(!qq){if(errEl)errEl.textContent='请输入QQ号';return;}if(!/^\d{5,12}$/.test(qq)){if(errEl)errEl.textContent='请输入正确的QQ号';return;}if(!pass){if(errEl)errEl.textContent='请输入密码';return;}if(pass.length<6){if(errEl)errEl.textContent='密码至少6位';return;}if(errEl)errEl.textContent='';var email=fakeEmail(qq);if(btn)btn.disabled=true;if(bt)bt.innerHTML='登录中…';try{if(isReg2){var nameEl=$('regName'),p2El=$('regPass2'),invEl=$('regInvite'),capEl=$('regCaptcha');var name=nameEl?nameEl.value.trim():'',p2=p2El?p2El.value:'',inv=invEl?invEl.value.trim():'';if(!name||name.length<2){if(errEl)errEl.textContent='用户名至少2个字';if(btn)btn.disabled=false;if(bt)bt.textContent='注 册';return;}if(pass!==p2){if(errEl)errEl.textContent='两次密码不一致';if(btn)btn.disabled=false;if(bt)bt.textContent='注 册';return;}if(!captchaCode||!capEl||capEl.value.trim().toUpperCase()!==captchaCode){if(errEl)errEl.textContent='验证码错误';drawCaptcha();if(btn)btn.disabled=false;if(bt)bt.textContent='注 册';return;}var r=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email:email,password:pass,data:{nickname:name,qq:qq}})});if(r&&r.access_token){localStorage.setItem('sb_token',r.access_token);localStorage.setItem('sb_refresh',r.refresh_token);localStorage.setItem('sb_user',JSON.stringify(r.user));await afterLogin(r.user);if(inv)dbR('apply_invite',{p_invite_code:inv.toUpperCase()}).then(function(x){if(x==='OK')toast('🎉邀请成功+25硬币');}).catch(function(){});}else{if(errEl)errEl.textContent='注册失败：该QQ号可能已注册';}}else{var r2=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:email,password:pass})});if(r2&&r2.access_token){localStorage.setItem('sb_token',r2.access_token);localStorage.setItem('sb_refresh',r2.refresh_token);localStorage.setItem('sb_user',JSON.stringify(r2.user));afterLogin(r2.user);}else{if(errEl)errEl.textContent='登录失败：QQ号或密码错误，未注册请先注册';}}}catch(e){if(errEl)errEl.textContent='操作失败：'+e.message;}if(btn)btn.disabled=false;if(bt)bt.textContent=isReg2?'注 册':'登 录';}
async function afterLogin(u){try{var b=await dbR('is_device_banned',{dev:did()});if(b){logout();toast('🚫该设备已被封禁');return;}await dbU('profiles','id=eq.'+u.id,{device_id:did()});}catch(e){}showMain();}
function logout(){localStorage.removeItem('sb_token');localStorage.removeItem('sb_refresh');localStorage.removeItem('sb_user');location.reload();}
function curUser2(){try{return JSON.parse(localStorage.getItem('sb_user'));}catch(e){return null;}}
async function fetchMe(){var u=curUser2();if(!u)return null;try{var r=await api('/rest/v1/profiles?select=*&id=eq.'+u.id);return r&&r[0]||null;}catch(e){return null;}}
async function showMain(){me=await fetchMe();if(!me)me={nickname:'花友',level:1,exp:0,coins:0,credit:100,role:'user'};var ta=$('topAvatar');if(ta){ta.textContent=me.nickname?me.nickname[0]:'友';if(me.avatar_url)ta.innerHTML='<img src="'+esc(me.avatar_url)+'">';}loadInfoCount();goPage('mainPage');try{initAds();loadSpot();}catch(e){}if(!localStorage.getItem('hxs_welcomed')){var wb=$('welcomeBody'),wm=$('welcomeModal');if(wb)wb.innerHTML=WELCOME.replace(/\n/g,'<br>');if(wm)wm.classList.add('show');localStorage.setItem('hxs_welcomed','1');}}
function goGuest(){me=null;localStorage.removeItem('sb_token');localStorage.removeItem('sb_refresh');localStorage.removeItem('sb_user');showMain();}
function closeWelcome(){var wm=$('welcomeModal');if(wm)wm.classList.remove('show');}

function goPage(id){try{document.querySelectorAll('.page').forEach(function(p){p.classList.remove('active');});}catch(e){}var el=$(id);if(!el)return;el.classList.add('active');try{var bn=document.querySelectorAll('#bottomNav .nav-item');bn.forEach(function(n){n.classList.toggle('on',n.dataset.p===id);});}catch(e){}if(id==='mainPage'){if(!searching)loadPosts();}else if(id==='postPage'){if(me)initPost();else needLogin();}else if(id==='mePage'){if(me){loadMe();loadHistory();}else needLogin();}else if(id==='editPage'){if(me)initEdit();else needLogin();}else if(id==='beautyPage'){if(me)initBeauty();else needLogin();}else if(id==='invitePage'){if(me){loadInvite();loadInvited();}else needLogin();}else if(id==='groupPage')loadGroup();else if(id==='signPage'){if(me)loadSign();else needLogin();}else if(id==='rankPage')loadRank2(rank);else if(id==='rulesPage'){var rb=$('rulesBox');if(rb)rb.innerHTML=RULES.replace(/\n/g,'<br>');}else if(id==='resourcePage'){loadRes(resType);var rpb=$('resPostBtn');if(rpb)rpb.style.display=(me&&me.role==='admin')?'block':'none';}else if(id==='resPostPage'){if(me&&me.role==='admin')initResPost();else needLogin();}else if(id==='adminPage'){if(me&&me.role==='admin')loadAdmin('reports');else needLogin();}else if(id==='coursePage')renderCourses();else if(id==='infoPage'){if(me)loadInfo();else needLogin();}else if(id==='favPage'){if(me)loadFavs(favType);else needLogin();}else if(id==='pomoPage'){if(me)initPomo();else needLogin();}else if(id==='friendPage'){if(me)loadFriends(friendType);else needLogin();}else if(id==='commentDetailPage'){if(!currentCmId)goPage('detailPage');}if(id!=='detailPage'&&id!=='commentDetailPage'){var cmb=$('cmBar');if(cmb)cmb.style.display='none';replyTo=null;}}
try{var bn2=document.querySelectorAll('#bottomNav .nav-item');bn2.forEach(function(n){n.onclick=function(){goPage(n.dataset.p);};});}catch(e){}
function needLogin(){goPage('loginPage');}
function goMe(){if(me)goPage('mePage');else needLogin();}
function goPost(){if(me)goPage('postPage');else{toast('请先登录');needLogin();}}
function goInfo(){if(me)goPage('infoPage');else needLogin();}
function exitDetail(){goPage('mainPage');var cmb=$('cmBar');if(cmb)cmb.style.display='none';replyTo=null;}
function rCode(){var s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',r='';for(var i=0;i<4;i++)r+=s[Math.floor(Math.random()*s.length)];return r;}
function resetAfk(){if(afkT)clearTimeout(afkT);afkT=setTimeout(function(){},7200000);}

function initAds(){try{var at=$('adTrack'),ad=$('adDots');if(!at||!ad)return;at.innerHTML=ADS.map(function(a){return'<div class="ad-item" onclick="location.href=\''+a.u+'\'"><div style="font-size:14px;font-weight:700">'+a.t+'</div><div style="font-size:12px;opacity:.9;margin-top:2px">'+a.s+'</div></div>';}).join('');ad.innerHTML=ADS.map(function(_,i){return'<span class="'+(i===0?'on':'')+'"></span>';}).join('');adIdx=0;if(adT)clearInterval(adT);adT=setInterval(function(){adIdx=(adIdx+1)%ADS.length;at.style.transform='translateX(-'+(adIdx*100)+'%)';var dots=ad.querySelectorAll('span');dots.forEach(function(s,i){s.classList.toggle('on',i===adIdx);});},4000);}catch(e){}}

async function loadSpot(){if(curBoard!=='jinghua'){var sp=$('spotlight');if(sp)sp.style.display='none';return;}var sp=$('spotlight');if(!sp)return;sp.style.display='block';var h='<div class="dc-grad">🌸 每日速递</div>';
try{var n=await fetch('https://api.magicalbox.cn/api3/tool/api/getMorningPaper');var nj=await n.json();if(nj&&nj.data){h+='<div class="dc-card"><div class="dc-h">» 60秒早报 <span style="margin-left:auto;color:#999;font-size:10px">'+nj.data.date+'</span></div>';var arr=nj.data.news||[];for(var i=0;i<arr.length&&i<12;i++){h+='<div class="dc-item"><b>'+(i+1)+'.</b> '+esc(arr[i])+'</div>';}if(nj.data.image)h+='<div class="dc-item" style="color:#7B68EE" onclick="window.open(\''+nj.data.image+'\')">🖼️ 完整早报图 →</div>';h+='</div>';}}catch(e){}
try{var e=await fetch('https://apiv3.shanbay.com/weapps/dailyquote/quote');var ej=await e.json();if(ej&&ej.content)h+='<div class="dc-card"><div class="dc-h">» 🇬🇧 每日英语</div><div class="dc-en">"'+esc(ej.content)+'"</div>'+(ej.translation?'<div class="dc-cn">'+esc(ej.translation)+(ej.author?' · '+esc(ej.author):'')+'</div>':'')+'</div>';}catch(e){}
try{var q=await fetch('https://v1.hitokoto.cn/');var qj=await q.json();if(qj&&qj.hitokoto)h+='<div class="dc-card"><div class="dc-h">» 💬 每日一言</div><div class="dc-quote">"'+esc(qj.hitokoto)+'"</div>'+(qj.from?'<div class="dc-cn" style="text-align:center">—— '+esc(qj.from)+'</div>':'')+'</div>';}catch(e){}
try{var nw=await fetch('https://apis.tianapi.com/generalnews/index?key='+TIANAPI_KEY+'&num=8');var nwj=await nw.json();if(nwj&&nwj.code===200&&nwj.result&&nwj.result.newslist){h+='<div class="dc-card"><div class="dc-h">» 📰 新闻资讯</div>';nwj.result.newslist.forEach(function(n,i){h+='<div class="dc-item" onclick="window.open(\''+n.url+'\')"><b>'+(i+1)+'.</b> '+esc(n.title)+'</div>';});h+='</div>';}}catch(e){}
try{var g=await fetch('http://8.134.118.1:9090/days/apps/getHistory');var gt=await g.text();var parts=gt.split('%%%').filter(function(x){return x.trim()&&x.trim()!=='true';});var hi=0;h+='<div class="dc-card"><div class="dc-h">» 📜 历史上的今天</div>';parts.forEach(function(p){try{var j=JSON.parse(p.trim());if(j&&j.title&&hi<5){h+='<div class="dc-item" onclick="window.open(\''+(j.link||'')+'\')"><b>'+esc(String(j.year||'').replace('年',''))+'</b>· '+esc(String(j.title).replace(/<[^>]+>/g,''))+'</div>';hi++;}}catch(e){}});h+='</div>';}catch(e){}
try{var dh=await fetch('https://apis.tianapi.com/douyinhot/index?key='+TIANAPI_KEY);var dhj=await dh.json();if(dhj&&dhj.code===200&&dhj.result&&dhj.result.list){h+='<div class="dc-card"><div class="dc-h">» 🎵 抖音热搜 TOP10</div>';dhj.result.list.slice(0,10).forEach(function(r,i){h+='<div class="dc-item" onclick="window.open(\'https://www.douyin.com/search/'+encodeURIComponent(r.word)+'\')"><b>'+(i+1)+'.</b> '+esc(r.word)+'</div>';});h+='</div>';}}catch(e){}
try{var th=await fetch('https://apis.tianapi.com/toutiaohot/index?key='+TIANAPI_KEY);var thj=await th.json();if(thj&&thj.code===200&&thj.result&&thj.result.list){h+='<div class="dc-card"><div class="dc-h">» 📰 头条热搜 TOP10</div>';thj.result.list.slice(0,10).forEach(function(r,i){h+='<div class="dc-item" onclick="window.open(\'https://www.toutiao.com/search?keyword='+encodeURIComponent(r.word)+'\')"><b>'+(i+1)+'.</b> '+esc(r.word)+'</div>';});h+='</div>';}}catch(e){}
try{var qwh=await fetch('https://apis.tianapi.com/nethot/index?key='+TIANAPI_KEY);var qwhj=await qwh.json();if(qwhj&&qwhj.code===200&&qwhj.result&&qwhj.result.list){h+='<div class="dc-card"><div class="dc-h">» 🌐 全网热搜 TOP10</div>';qwhj.result.list.slice(0,10).forEach(function(r,i){h+='<div class="dc-item" onclick="window.open(\'https://www.baidu.com/s?wd='+encodeURIComponent(r.keyword)+'\')"><b>'+(i+1)+'.</b> '+esc(r.keyword)+'</div>';});h+='</div>';}}catch(e){}
try{var wh=await fetch('https://apis.tianapi.com/weibohot/index?key='+TIANAPI_KEY);var whj=await wh.json();if(whj&&whj.code===200&&whj.result&&whj.result.list){h+='<div class="dc-card"><div class="dc-h">» 💬 微博热搜 TOP10</div>';whj.result.list.slice(0,10).forEach(function(r,i){h+='<div class="dc-item" onclick="window.open(\'https://s.weibo.com/weibo?q='+encodeURIComponent(r.hotword)+'\')"><b>'+(i+1)+'.</b> '+esc(r.hotword)+'</div>';});h+='</div>';}}catch(e){}
try{var bili=await fetch('https://api.bilibili.com/x/web-interface/popular?ps=10');var bilij=await bili.json();if(bilij&&bilij.code===0&&bilij.data&&bilij.data.list){h+='<div class="dc-card"><div class="dc-h">» 📺 B站热门 TOP10</div>';bilij.data.list.forEach(function(r,i){h+='<div class="dc-item" onclick="window.open(\'https://www.bilibili.com/video/av'+r.aid+'\')"><b>'+(i+1)+'.</b> '+esc(r.title)+'</div>';});h+='</div>';}}catch(e){}
h+='<div class="dc-card"><div class="dc-h">» 📡 更多平台</div><div style="display:flex;flex-wrap:wrap;gap:6px">';[{n:'知乎热门',u:'https://www.zhihu.com/hot'},{n:'腾讯新闻',u:'https://news.qq.com/'},{n:'网易新闻',u:'https://news.163.com/'},{n:'百度热搜',u:'https://top.baidu.com/board'}].forEach(function(x){h+='<span class="chip" style="cursor:pointer" onclick="window.open(\''+x.u+'\')">'+x.n+'</span>';});h+='</div></div>';
sp.innerHTML=h;if(spT)clearInterval(spT);spT=setInterval(function(){if(curBoard==='jinghua')loadSpot();},28800000);}

function renderBoards(){var box=$('boards');if(!box)return;box.innerHTML=BOARDS.map(function(b){return'<div class="board-tab '+(b.key===curBoard&&!searching?'on':'')+'" data-k="'+b.key+'">'+b.name+'</div>';}).join('');box.querySelectorAll('.board-tab').forEach(function(t){t.onclick=function(){searching=false;var si=$('searchInput');if(si)si.value='';curBoard=t.dataset.k;renderBoards();loadPosts();};});}
function doSearch(){searching=true;var si=$('searchInput'),pl=$('postList');if(!si||!pl)return;var kw=si.value.trim();pl.innerHTML='<div class="empty">搜索中...</div>';api('/rest/v1/posts?select=*,author_id(nickname,level,qq,id)&status=eq.published&or=(title.ilike.*'+encodeURIComponent(kw)+'*,content.ilike.*'+encodeURIComponent(kw)+'*)&order=created_at.desc&limit=50').then(function(d){renderCards(d,pl,'没搜到');}).catch(function(){pl.innerHTML='<div class="empty">搜索失败</div>';});}
async function loadPosts(){renderBoards();try{initAds();loadSpot();}catch(e){}if(searching){doSearch();return;}var pl=$('postList');if(!pl)return;pl.innerHTML='<div class="empty">加载中...</div>';try{var order='created_at.desc';if(sort==='like')order='like_count.desc';else if(sort==='fav')order='good_count.desc';else if(sort==='view')order='view_count.desc';var cond;if(curBoard==='jinghua')cond=qs({status:'eq.published',is_featured:'eq.true',select:'*,author_id(nickname,level,qq,id)',order:order,limit:'50'});else if(curBoard==='remen')cond=qs({status:'eq.published',select:'*,author_id(nickname,level,qq,id)',order:'(like_count*2+good_count*3+coin_count).desc',limit:'50'});else cond=qs({status:'eq.published',board:'eq.'+curBoard,select:'*,author_id(nickname,level,qq,id)',order:order,limit:'50'});var d=await api('/rest/v1/posts?'+cond);renderCards(d,pl,'这个板块还没有帖子✨');}catch(e){pl.innerHTML='<div class="empty">加载失败</div>';}}
try{var sb=$('sortBar');if(sb)sb.querySelectorAll('span').forEach(function(s){s.onclick=function(){sort=s.dataset.s;var sbs=$('sortBar');if(sbs)sbs.querySelectorAll('span').forEach(function(x){x.classList.toggle('on',x.dataset.s===sort);});loadPosts();};});}catch(e){}
function renderCards(d,box,emptyTxt){if(!box)return;if(!d||!d.length){box.innerHTML='<div class="empty">'+(emptyTxt||'暂无')+'</div>';return;}box.innerHTML=d.map(function(p){var img=p.images&&p.images[0]?'<div class="wm" style="position:relative"><img class="pc-img" src="'+esc(p.images[0])+'" onerror="this.parentNode.style.display=\'none\'"></div>':'';return'<div class="post-card" onclick="openPost('+p.id+')"><div class="pc-title">'+esc(p.title)+(p.is_featured?'🏆':'')+'</div><div class="pc-body">'+esc(p.content)+'</div>'+img+'<div class="pc-meta"><span style="cursor:pointer" onclick="event.stopPropagation();openUser(\''+(p.author_id?p.author_id.id||'':'')+'\')">👤'+esc(p.author_id?p.author_id.nickname||'花友':'花友')+'<span class="lv">Lv'+(p.author_id?p.author_id.level||1:1)+'</span></span><span>👍'+p.like_count+'</span><span>⭐'+(p.fav_count||0)+'</span><span>🪙'+p.coin_count+'</span><span style="margin-left:auto">'+fmt(p.created_at)+'</span></div></div>';}).join('');}
async function openPost(id){try{var r=await api('/rest/v1/posts?select=*,author_id(nickname,level,qq,id,avatar_url,role)&id=eq.'+id);if(!r||!r[0])return;curPost=r[0];}catch(e){return;}if(me){dbI('history',{user_id:me.id,post_id:id}).catch(function(){});dbR('add_view',{pid:id}).catch(function(){});curPost.view_count=(curPost.view_count||0)+1;}var d=curPost,fav=me?await isFav('post',d.id):false;var isAuthor=me&&d.author_id&&d.author_id.id===me.id;var isAdmin=me&&me.role==='admin';var img=d.images&&d.images[0]?'<div class="wm" style="position:relative;margin-top:8px"><img src="'+esc(d.images[0])+'" style="width:100%;border-radius:8px" onerror="this.parentNode.style.display=\'none\'"></div>':'';var authorTag=d.author_id&&d.author_id.role==='admin'?'<span class="tag-admin">管理</span>':'<span class="tag-beta">公测用户</span>';var fol=me&&!isAuthor?await isFollowing(d.author_id.id):null;var followBtn=isAuthor?'':(me?'<button class="follow-btn '+(fol?'':'')+'" style="background:'+(fol?'#eee':'linear-gradient(135deg,#7B68EE,#6A5ACD)')+';color:'+(fol?'#555':'#fff')+'" onclick="'+(fol?'unfollowFromDetail(\''+d.author_id.id+'\')':'followFromDetail(\''+d.author_id.id+'\')')+'">'+(fol?'已关注':'＋关注')+'</button>':'');
var db=$('detailBox');if(!db)return;db.innerHTML='<div class="detail-top"><div class="dt-avatar" onclick="openUser(\''+(d.author_id?d.author_id.id||'':'')+'\')">'+(d.author_id&&d.author_id.avatar_url?'<img src="'+esc(d.author_id.avatar_url)+'">':esc((d.author_id?d.author_id.nickname||'友':'友')[0]))+'</div><div style="flex:1"><div style="font-size:15px;font-weight:600;cursor:pointer" onclick="openUser(\''+(d.author_id?d.author_id.id||'':'')+'\')">'+esc(d.author_id?d.author_id.nickname||'花友':'花友')+authorTag+'</div><div style="font-size:11px;color:#999">'+fmtFull(d.created_at)+'</div></div>'+followBtn+'</div><div class="detail-title">'+esc(d.title)+(d.is_featured?'🏆':'')+'</div><div class="detail-body">'+esc(d.content)+'</div>'+img;
var acts='<div class="detail-actions"><button class="action-btn '+(isLiked(d.id)?'on':'')+'" onclick="likePost()">👍'+(d.like_count||0)+'</button><button class="action-btn '+(fav?'on':'')+'" style="border-color:#7B68EE;color:#7B68EE" onclick="toggleFav()">⭐'+(fav?'已收藏':'收藏')+'</button><button class="action-btn" style="border-color:#ff9500;color:#ff9500" onclick="openTip()">🎁打赏</button><button class="action-btn" style="border-color:#7C6FF0;color:#7C6FF0" onclick="doTip(\'good\',0)">❤️好评</button><button class="action-btn" onclick="openCommentInput()">💬评论</button>';
var canReport=!(d.author_id&&d.author_id.role==='admin');if(canReport)acts+='<button class="action-btn" onclick="openReport(\'post\','+d.id+')">🚩举报</button>';
if(isAuthor||isAdmin)acts+='<button class="action-btn" style="color:#e5484d" onclick="deletePost('+d.id+')">🗑删除</button>';
acts+='</div>';db.innerHTML+=acts;var cmb=$('cmBar');if(cmb)cmb.style.display=me?'flex':'none';replyTo=null;loadComments(id);goPage('detailPage');}
function openCommentInput(){var ci=$('cmInput');if(!ci)return;ci.focus();}
async function isFollowing(uid){if(!me)return false;try{var r=await api('/rest/v1/followers?follower_id=eq.'+me.id+'&following_id=eq.'+uid+'&limit=1');return r&&r.length>0;}catch(e){return false;}}
async function followFromDetail(uid){if(!me){toast('请先登录');needLogin();return;}try{var r=await dbR('follow_user',{p_following_id:uid});toast(r==='OK'?'✅已关注':r);openPost(curPost.id);}catch(e){toast('失败');}}
async function unfollowFromDetail(uid){try{await dbR('unfollow_user',{p_following_id:uid});toast('已取消关注');openPost(curPost.id);}catch(e){toast('失败');}}
function isLiked(id){return(JSON.parse(localStorage.getItem('liked')||'[]')).indexOf(id)>-1;}
async function likePost(){if(!me){toast('请先登录');needLogin();return;}var l=JSON.parse(localStorage.getItem('liked')||'[]');if(l.indexOf(curPost.id)>-1)return;l.push(curPost.id);localStorage.setItem('liked',JSON.stringify(l));try{await dbU('posts','id=eq.'+curPost.id,{like_count:(curPost.like_count||0)+1});curPost.like_count++;if(curPost.author_id&&curPost.author_id.id!==me.id)dbR('notify_user',{p_user_id:curPost.author_id.id,p_type:'like',p_content:me.nickname+'点赞了你的帖子'}).catch(function(){});}catch(e){toast('点赞失败');}}
async function deletePost(pid){if(!confirm('确定删除？'))return;try{var r=await dbR('delete_post',{pid:pid});toast(r==='OK'?'✅已删除':('⚠️'+r));if(r==='OK')goPage('mainPage');}catch(e){toast('删除失败：'+e.message);}}
function openTip(){if(!me){toast('请先登录');needLogin();return;}if(curPost.author_id&&curPost.author_id.id===me.id){toast('不能打赏自己');return;}var ta=$('tipAmount');if(ta)ta.value=1;var tm=$('tipModal');if(tm)tm.classList.add('show');}
function hideTip(){var tm=$('tipModal');if(tm)tm.classList.remove('show');}
async function doTip(kind,amount){try{var r=await dbR('tip_post',{p_post_id:curPost.id,p_kind:kind,p_amount:parseInt(amount)||1});toast(r||'操作失败');hideTip();setTimeout(function(){openPost(curPost.id);},700);}catch(e){toast('失败：'+e.message);}}
function openReport(type,tid){if(!me){toast('请先登录');needLogin();return;}var rr=$('reportReasons'),ro=$('reportOther');if(!rr)return;var rs=['色情低俗','引战辱骂','广告引流','其他'];rr.innerHTML=rs.map(function(r,i){return'<label style="display:block;padding:8px 0;border-bottom:1px solid #f4f4f4;font-size:13px"><input type="radio" name="rr" class="rr" data-i="'+i+'" style="margin-right:8px">'+r+'</label>';}).join('')+'<button class="btn" style="margin-top:10px" onclick="submitReport(\''+type+'\','+tid+')">提交举报</button>';if(ro)ro.style.display='none';var rm=$('reportModal');if(rm)rm.classList.add('show');document.querySelectorAll('.rr').forEach(function(x){x.onchange=function(){var ro2=$('reportOther');if(ro2)ro2.style.display=this.dataset.i=='3'?'block':'none';};});}
function hideReport(){var rm=$('reportModal');if(rm)rm.classList.remove('show');}
async function submitReport(type,tid){var sel='';var checked=document.querySelectorAll('.rr:checked');if(checked.length)sel=REPORT_REASONS2[+checked[0].dataset.i];if(sel==='其他'){var ot=$('reportOtherText');if(ot&&!ot.value.trim()){toast('请填写举报原因');return;}sel=ot?ot.value.trim():'其他';}if(!sel){toast('请选择举报原因');return;}try{await dbI('reports',{target_type:type,target_id:tid,reason:sel,reporter_id:me.id});toast('🚩举报成功，成立有奖');hideReport();}catch(e){toast('举报失败');}}
var REPORT_REASONS2=['色情低俗','引战辱骂','广告引流','其他'];

function pickCmImg(){var f=$('cmImg');if(!f||!f.files||!f.files[0])return;cmImg=f.files[0];var cd=$('cmDel');if(cd)cd.style.display='inline';toast('📷已选图片');}
function cancelCmImg(){cmImg=null;var ci=$('cmImg'),cd=$('cmDel');if(ci)ci.value='';if(cd)cd.style.display='none';}
function pickImg(inp,prevId){var f=inp.files&&inp.files[0];if(!f)return;var img=URL.createObjectURL(f);var prev=$(prevId);if(!prev)return;prev.innerHTML='<div class="img-preview-wrap"><img src="'+img+'"><span class="cancel-img" onclick="document.getElementById(\''+prevId+'\').innerHTML=\'\'">✕</span></div>';inp._selected=f;}
async function loadComments(pid){var cl=$('commentList');if(!cl)return;try{var d=await api('/rest/v1/comments?select=*,author_id(nickname,level,id,role)&post_id=eq.'+pid+'&status=eq.published&order=created_at.asc');if(!d||!d.length){cl.innerHTML='<div class="empty" style="padding:14px 0">还没有评论</div>';return;}cl.innerHTML=d.map(function(c){var tag=c.author_id&&c.author_id.role==='admin'?'<span class="tag-admin">管理</span>':'<span class="tag-beta">公测用户</span>';var canReport=!(c.author_id&&c.author_id.role==='admin');return'<div class="comment-box" id="cm'+c.id+'" oncontextmenu="event.preventDefault();showCtx(event,'+c.id+')" ontouchstart="ctxStart(event,'+c.id+')" ontouchend="ctxEnd()"><div class="cb-name" onclick="openUser(\''+(c.author_id?c.author_id.id||'':'')+'\')">👤'+esc(c.author_id?c.author_id.nickname||'花友':'花友')+tag+'</div><div class="cb-text" onclick="openCommentDetail('+c.id+')">'+esc(c.content)+'</div>'+(c.image?'<img class="cb-img" src="'+esc(c.image)+'" onerror="this.style.display=\'none\'">':'')+'<div class="cb-time">'+fmt(c.created_at)+'</div><div class="cb-acts"><span onclick="replyTo('+c.id+',\''+esc(c.author_id?c.author_id.nickname||'':'')+'\')">💬回复</span><span onclick="likeCm('+c.id+')">👍'+(c.like_count||0)+'</span>'+(canReport?'<span onclick="openReport(\'comment\','+c.id+')">🚩</span>':'')+(me&&(me.id===c.author_id.id||me.role==='admin'||(curPost&&curPost.author_id&&curPost.author_id.id===me.id))?'<span onclick="delCm('+c.id+')">🗑</span>':'')+'</div></div>';}).join('');}catch(e){cl.innerHTML='<div class="empty">加载失败</div>';}}
function ctxStart(e,cid){ctxTimer=setTimeout(function(){showCtx(e,cid);},500);}
function ctxEnd(){clearTimeout(ctxTimer);}
function showCtx(e,cid){clearTimeout(ctxTimer);currentCmId=cid;var menu=$('ctxMenu');if(!menu)return;var html='<div class="cm-i" onclick="copyCm()">📋 复制评论</div>';var cm=document.querySelector('#cm'+cid);var canReport=!(cm&&cm.dataset&&false);api('/rest/v1/comments?select=*,author_id(nickname,role,id)&id=eq.'+cid).then(function(d){var c=d&&d[0];if(!c)return;var isAdminC=c.author_id&&c.author_id.role==='admin';if(!isAdminC)html+='<div class="cm-i" onclick="openReport(\'comment\','+cid+');hideCtx()">🚩 举报评论</div>';if(me&&(me.id===c.author_id.id||me.role==='admin'||(curPost&&curPost.author_id&&curPost.author_id.id===me.id)))html+='<div class="cm-i" style="color:#e5484d" onclick="delCm('+cid+');hideCtx()">🗑 删除评论</div>';html+='<div class="cm-i" onclick="hideCtx()">取消</div>';menu.innerHTML=html;menu.style.display='block';var x=e.touches?e.touches[0].clientX:e.clientX,y=e.touches?e.touches[0].clientY:e.clientY;menu.style.left=x+'px';menu.style.top=y+'px';});}
function hideCtx(){var menu=$('ctxMenu');if(menu)menu.style.display='none';}
function copyCm(){var cm=$('#cm'+currentCmId);if(cm){var t=cm.querySelector('.cb-text');if(t){var ta=document.createElement('textarea');ta.value=t.textContent;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);toast('✅已复制');}}hideCtx();}
async function openCommentDetail(cid){currentCmId=cid;try{var r=await api('/rest/v1/comments?select=*,author_id(nickname,level,id,role)&id=eq.'+cid);var c=r&&r[0];if(!c)return;var tag=c.author_id&&c.author_id.role==='admin'?'<span class="tag-admin">管理</span>':'<span class="tag-beta">公测用户</span>';var cm=$('cdMain');if(cm)cm.innerHTML='<div class="comment-box"><div class="cb-name" onclick="openUser(\''+(c.author_id?c.author_id.id||'':'')+'\')">👤'+esc(c.author_id?c.author_id.nickname||'花友':'花友')+tag+'</div><div class="cb-text">'+esc(c.content)+'</div><div class="cb-time">'+fmt(c.created_at)+'</div></div>';var replies=await api('/rest/v1/comments?select=*,author_id(nickname,id,role)&reply_to=eq.'+cid+'&status=eq.published&order=created_at.asc');var rl=$('cdReplies');if(rl)rl.innerHTML=(!replies||!replies.length)?'<div class="empty" style="padding:14px 0">还没有回复</div>':replies.map(function(rp){var rt=rp.author_id&&rp.author_id.role==='admin'?'<span class="tag-admin">管理</span>':'';return'<div class="cb-reply" style="background:#f7f8fa;border-radius:8px;padding:8px;margin-bottom:6px;font-size:13px" oncontextmenu="event.preventDefault();showCtx(event,'+rp.id+')"><b>'+esc(rp.author_id?rp.author_id.nickname||'':'')+'</b>'+rt+'：'+esc(rp.content)+'</div>';}).join('');$('cmBar').style.display='flex';replyTo=cid;$('cmInput').placeholder='回复该评论…';goPage('commentDetailPage');}catch(e){toast('加载失败');}}
async function likeCm(cid){if(!me){toast('请先登录');needLogin();return;}try{var cur=await api('/rest/v1/comments?select=like_count&id=eq.'+cid);await dbU('comments','id=eq.'+cid,{like_count:(cur&&cur[0]?cur[0].like_count:0)+1});toast('👍');loadComments(curPost.id);}catch(e){toast('失败');}}
function replyTo(cid,name){if(!me){toast('请先登录');needLogin();return;}replyTo=cid;var ci=$('cmInput'),cb=$('cmBar');if(ci)ci.placeholder='回复 @'+name;if(ci)ci.focus();if(cb)cb.style.display='flex';}
async function submitComment(){if(!me){toast('请先登录');needLogin();return;}var ci=$('cmInput');var c=ci?ci.value.trim():'';if(!c&&!cmImg)return;try{var image='';if(cmImg){try{image=await uploadImg(cmImg);}catch(e){toast('图片上传失败');return;}}var r=await dbI('comments',{post_id:curPost.id,author_id:me.id,content:c,image:image,reply_to:replyTo});if(r&&r[0]&&r[0].status==='rejected')toast('🚫'+r[0].reject_reason);else{if(ci)ci.value='';if(ci)ci.placeholder='友善评论…';cmImg=null;var cim=$('cmImg'),cd=$('cmDel');if(cim)cim.value='';if(cd)cd.style.display='none';if(currentCmId&&replyTo)openCommentDetail(currentCmId);else{replyTo=null;if(curPost.author_id&&curPost.author_id.id!==me.id)dbR('notify_user',{p_user_id:curPost.author_id.id,p_type:'comment',p_content:me.nickname+'评论了「'+(curPost.title||'').slice(0,10)+'」'}).catch(function(){});loadComments(curPost.id);}}}catch(e){toast('发布失败：'+e.message);}}
async function delCm(cid){if(!confirm('确定删除？奖励扣回+50%罚金'))return;try{var r=await dbR('delete_comment',{cid:cid});toast(r==='OK'?'✅已删除':('⚠️'+r));if(r==='OK'){if(currentCmId===cid){goPage('detailPage');}loadComments(curPost.id);}}catch(e){toast('删除失败');}}
async function favCm(cid){if(!me){toast('请先登录');needLogin();return;}try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.comment&target_id=eq.'+cid+'&limit=1');if(r&&r.length){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.comment&target_id=eq.'+cid);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:'comment',target_id:cid});toast('⭐已收藏');}}catch(e){toast('失败');}}
async function isFav(type,tid){if(!me)return false;try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.'+type+'&target_id=eq.'+tid+'&limit=1');return r&&r.length>0;}catch(e){return false;}}
async function toggleFav(){if(!me){toast('请先登录');needLogin();return;}var fav=await isFav('post',curPost.id);try{if(fav){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.post&target_id=eq.'+curPost.id);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:'post',target_id:curPost.id});toast('⭐已收藏');if(curPost.author_id&&curPost.author_id.id!==me.id)dbR('notify_user',{p_user_id:curPost.author_id.id,p_type:'fav',p_content:me.nickname+'收藏了你的帖子'}).catch(function(){});}openPost(curPost.id);}catch(e){toast('失败');}}
async function loadFavs(type){favType=type;['app','course','post','comment'].forEach(function(t,i){var el=$('favTab'+(i+1));if(el)el.classList.toggle('on',t===type);});var fl=$('favList');if(!fl)return;fl.innerHTML='<div class="empty">加载中...</div>';if(!me){fl.innerHTML='<div class="empty">请先登录</div>';return;}var fs=$('favSearch');var kw=fs?fs.value.trim():'';try{var favs=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.'+type+'&order=created_at.desc&limit=100');if(!favs||!favs.length){fl.innerHTML='<div class="empty">还没有收藏</div>';return;}if(type==='post'){var ids=favs.map(function(f){return f.target_id;});var posts=await api('/rest/v1/posts?select=*,author_id(nickname,level)&id=in.('+ids.join(',')+')&status=eq.published');var items=posts||[];if(kw)items=items.filter(function(p){return p.title.indexOf(kw)>-1||p.content.indexOf(kw)>-1;});fl.innerHTML=items.length?items.map(function(p){return'<div class="his-card" onclick="openPost('+p.id+')"><span style="flex:1;font-size:13px">'+esc(p.title)+'</span></div>';}).join(''):'<div class="empty">没搜到</div>';}else if(type==='comment'){var ids2=favs.map(function(f){return f.target_id;});var cmts=await api('/rest/v1/comments?select=*,author_id(nickname)&id=in.('+ids2.join(',')+')&status=eq.published');var items2=cmts||[];if(kw)items2=items2.filter(function(c){return c.content.indexOf(kw)>-1;});fl.innerHTML=items2.length?items2.map(function(c){return'<div class="comment-box"><div class="cb-text">'+esc(c.content)+'</div></div>';}).join(''):'<div class="empty">没搜到</div>';}else if(type==='app'){var ids3=favs.map(function(f){return f.target_id;});var res=await api('/rest/v1/resources?type=eq.app&id=in.('+ids3.join(',')+')');var items3=res||[];if(kw)items3=items3.filter(function(r){return r.title.indexOf(kw)>-1||(r.description||'').indexOf(kw)>-1;});fl.innerHTML=items3.length?items3.map(function(r){return'<div class="app-card" onclick="openAppDetail('+r.id+')"><div class="ac-top"><div class="ac-icon">'+(r.icon?'<img src="'+esc(r.icon)+'" class="ac-icon">':'📱')+'</div><div><div class="ac-title">'+esc(r.title)+'</div></div></div></div>';}).join(''):'<div class="empty">没搜到</div>';}else{var items4=COURSES.filter(function(c,i){return favs.some(function(f){return f.target_id===i;});});var list=kw?items4.filter(function(c){return c.t.indexOf(kw)>-1;}):items4;fl.innerHTML=list.length?list.map(function(c){return'<div class="his-card" onclick="location.href=\''+c.u+'\'"><span style="flex:1;font-size:13px">'+esc(c.t)+'</span></div>';}).join(''):'<div class="empty">没搜到</div>';}}catch(e){fl.innerHTML='<div class="empty">加载失败</div>';}}
async function uploadImg(file){var name=Date.now()+'-'+Math.random().toString(36).slice(2,6)+'.jpg';var res=await fetch(SUPABASE_URL+'/storage/v1/object/images/'+name,{method:'POST',headers:{...authH(),'Content-Type':file.type||'image/jpeg'},body:file});if(!res.ok){if(res.status===403)throw new Error('Storage权限不足，请跑SQL');if(res.status===404)throw new Error('Storage没有images桶，请创建');throw new Error('上传失败('+res.status+')');}return SUPABASE_URL+'/storage/v1/object/public/images/'+name;}
function initPost(){var bc=$('boardChips');if(!bc)return;bc.innerHTML=POST_BOARDS.map(function(b){return'<div class="chip '+(b.key===curBoard?'on':'')+'" data-k="'+b.key+'">'+b.name+'</div>';}).join('');bc.querySelectorAll('.chip').forEach(function(x){x.onclick=function(){bc.querySelectorAll('.chip').forEach(function(y){y.classList.remove('on');});x.classList.add('on');curBoard=x.dataset.k;};});var pe=$('postErr'),ip=$('imgPreview');if(pe)pe.textContent='';if(ip)ip.innerHTML='';}
async function submitPost(){if(!me){toast('请先登录');needLogin();return;}if(me&&me.banned_until&&new Date(me.banned_until)>new Date()){toast('⛔禁言中');return;}if(me&&me.is_banned){toast('⛔已封禁');return;}if(me&&me.level<2&&me.created_at&&new Date()-new Date(me.created_at)<86400000){toast('Lv.1新用户24h内仅浏览');return;}var pt=$('pTitle'),pc=$('pContent');if(!pt||!pc)return;var title=pt.value.trim(),content=pc.value.trim();if(!title||!content){var pe=$('postErr');if(pe)pe.textContent='请填写标题和内容';return;}if(title.replace(/[a-zA-Z0-9\s]/g,'').length<2){var pe2=$('postErr');if(pe2)pe2.textContent='标题至少2个汉字';return;}var images=[];var pi=$('pImg');var f=pi?pi._selected:null;try{if(f)images.push(await uploadImg(f));var r=await dbI('posts',{author_id:me.id,board:curBoard,title:title,content:content,images:images});if(r&&r[0]&&r[0].status==='rejected'){var pe3=$('postErr');if(pe3)pe3.textContent='🚫'+r[0].reject_reason;return;}var pe4=$('postErr');if(pe4)pe4.textContent='✅发布成功';if(pt)pt.value='';if(pc)pc.value='';if(pi){pi.value='';pi._selected=null;}var ip=$('imgPreview');if(ip)ip.innerHTML='';setTimeout(function(){goPage('mainPage');},700);}catch(e){var pe5=$('postErr');if(pe5)pe5.textContent='发布失败：'+e.message;}}
async function openUser(uid){if(!uid)return;curUser=uid;try{var r=await api('/rest/v1/profiles?select=*&id=eq.'+uid);var u=r&&r[0];if(!u){toast('用户不存在');return;}var isMe2=me&&me.id===uid;var fol=me?await api('/rest/v1/followers?follower_id=eq.'+me.id+'&following_id=eq.'+uid+'&limit=1'):null;var folN=await api('/rest/v1/followers?following_id=eq.'+uid+'&select=id');var fanN=await api('/rest/v1/followers?follower_id=eq.'+uid+'&select=id');var goodN=await api('/rest/v1/tips?select=id&to_user=eq.'+uid+'&kind=eq.good');var pct=Math.min(100,Math.round((u.exp-expLv(u.level))/(expLv(u.level+1)-expLv(u.level))*100));var tag=u.role==='admin'?'<span class="tag-admin">管理</span>':'<span class="tag-beta">公测用户</span>';var editBtn=isMe2?'<div style="margin-top:8px"><span style="background:#F0E6FF;color:#7B68EE;padding:5px 20px;border-radius:14px;font-size:12px;cursor:pointer" onclick="goPage(\'editPage\')">✏️ 编辑资料</span></div>':'';var folBtn=isMe2?'':'<button class="follow-btn '+(fol&&fol.length?'':'')+'" style="background:'+(fol&&fol.length?'#eee':'linear-gradient(135deg,#7B68EE,#6A5ACD)')+';color:'+(fol&&fol.length?'#555':'#fff')+'" onclick="'+(fol&&fol.length?'unfollowUser(\''+uid+'\')':'followUser(\''+uid+'\')')+'">'+(fol&&fol.length?'已关注':'＋关注')+'</button>';var ub=$('userBox');if(!ub)return;ub.innerHTML='<div class="ubg">'+(u.bg_image?'<img src="'+esc(u.bg_image)+'" onerror="this.parentNode.style.background=\'linear-gradient(135deg,#7B68EE,#6A5ACD)\'">':'')+'</div><div class="ubg-avatar-wrap"><div class="ubg-avatar2">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'">':esc((u.nickname||'友')[0]))+'</div></div><div class="uinfo"><div class="uname">'+esc(u.nickname)+tag+'</div><div class="pt-exp"><i style="width:'+Math.max(4,pct)+'%"></i></div><div class="pt-exp-t">Lv'+u.level+'·经验'+u.exp+'/'+expLv(u.level+1)+'</div><div style="font-size:12px;color:#666;margin-top:6px">'+esc(u.bio||'')+'</div><div class="stat-card" style="margin-top:8px"><div><div class="stat-num" style="color:#ff9500">🪙'+u.coins+'</div><div class="stat-label">硬币</div></div><div style="cursor:pointer" onclick="goFriends(\'following\')"><div class="stat-num" style="color:#7B68EE">'+(folN?folN.length:0)+'</div><div class="stat-label">关注</div></div><div style="cursor:pointer" onclick="goFriends(\'fans\')"><div class="stat-num" style="color:#6A5ACD">'+(fanN?fanN.length:0)+'</div><div class="stat-label">粉丝</div></div><div><div class="stat-num" style="color:#F5A623">'+(goodN?goodN.length:0)+'</div><div class="stat-label">好评</div></div></div>'+editBtn+folBtn+'</div>';loadUserPosts('posts');goPage('userPage');}catch(e){toast('加载失败');}}
function goFriends(t){friendType=t;goPage('friendPage');}
async function loadUserPosts(tab){try{var ut1=$('ut1'),ut2=$('ut2');if(ut1)ut1.classList.toggle('on',tab==='posts');if(ut2)ut2.classList.toggle('on',tab==='comments');var ul=$('userList');if(!ul)return;if(tab==='posts'){var d=await api('/rest/v1/posts?select=*,author_id(nickname,level)&author_id=eq.'+curUser+'&status=eq.published&order=created_at.desc&limit=50');renderUserPosts(d,ul);}else{var d2=await api('/rest/v1/comments?select=*,author_id(nickname,level)&author_id=eq.'+curUser+'&status=eq.published&order=created_at.desc&limit=50');ul.innerHTML=(!d2||!d2.length)?'<div class="empty">TA还没有评论</div>':d2.map(function(c){return'<div class="comment-box"><div style="font-size:11px;color:#999">📄 '+(curPost&&curPost.id===c.post_id?'当前帖子':'帖子#'+c.post_id)+'</div><div class="cb-text">'+esc(c.content)+'</div><div class="cb-acts"><span>👍'+(c.like_count||0)+'</span></div><div class="cb-time">'+fmtFull(c.created_at)+'</div></div>';}).join('');}}catch(e){var ul2=$('userList');if(ul2)ul2.innerHTML='<div class="empty">加载失败</div>';}}
function renderUserPosts(d,box){if(!d||!d.length){box.innerHTML='<div class="empty">TA还没有发过帖子</div>';return;}box.innerHTML=d.map(function(p){return'<div class="post-card" onclick="openPost('+p.id+')"><div style="font-size:10px;color:#7B68EE">'+p.board+'</div><div class="pc-title">'+esc(p.title)+'</div><div class="pc-body">'+esc(p.content)+'</div><div class="pc-meta"><span>👍'+p.like_count+'</span><span>⭐'+(p.fav_count||0)+'</span><span>🪙'+p.coin_count+'</span><span style="margin-left:auto">'+fmtFull(p.created_at)+'</span></div></div>';}).join('');}
async function followUser(uid){if(!me){toast('请先登录');needLogin();return;}try{var r=await dbR('follow_user',{p_following_id:uid});toast(r==='OK'?'✅已关注':r);openUser(uid);}catch(e){toast('失败');}}
async function unfollowUser(uid){try{await dbR('unfollow_user',{p_following_id:uid});toast('已取消关注');openUser(uid);}catch(e){toast('失败');}}

var HBAR=[['📅','签到','signPage'],['⭐','收藏','favPage'],['🏆','排行','rankPage'],['🎟️','邀请','invitePage'],['💬','交流群','groupPage'],['🛡️','后台','adminPage'],['🍅','番茄','pomoPage'],['🎨','美化','beautyPage'],['🚪','退出','logout']];
async function loadMe(){if(!me)return;var u=me;var folN=await api('/rest/v1/followers?following_id=eq.'+u.id+'&select=id').catch(function(){return[];});var fanN=await api('/rest/v1/followers?follower_id=eq.'+u.id+'&select=id').catch(function(){return[];});var goodN=await api('/rest/v1/tips?select=id&to_user=eq.'+u.id+'&kind=eq.good').catch(function(){return[];});var pct=Math.min(100,Math.round((u.exp-expLv(u.level))/(expLv(u.level+1)-expLv(u.level))*100));var tag=u.role==='admin'?'<span class="tag-admin">管理</span>':'';var credit=u.role==='admin'?'':'<span style="font-size:10px;color:#6A5ACD;margin-left:6px">💯'+u.credit+'</span>';var mp=$('meProfile');if(mp)mp.innerHTML='<div class="me-card" onclick="openUser(\''+u.id+'\')"><div class="me-avatar">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'">':esc((u.nickname||'友')[0]))+'</div><div style="flex:1"><div class="me-name">'+esc(u.nickname)+tag+credit+'</div><div class="pt-exp"><i style="width:'+Math.max(4,pct)+'%"></i></div><div class="pt-exp-t">Lv'+u.level+'·'+u.exp+'/'+expLv(u.level+1)+'</div></div><div class="me-arrow">›</div></div>';var ac=$('meAccount');if(ac)ac.innerHTML='<div class="acc-item" onclick="goFriends(\'following\')"><div class="acc-num" style="color:#ff9500">🪙'+u.coins+'</div><div class="acc-label">硬币</div></div><div class="acc-item" onclick="goFriends(\'following\')"><div class="acc-num" style="color:#7B68EE">'+(folN?folN.length:0)+'</div><div class="acc-label">关注</div></div><div class="acc-item" onclick="goFriends(\'fans\')"><div class="acc-num" style="color:#6A5ACD">'+(fanN?fanN.length:0)+'</div><div class="acc-label">粉丝</div></div><div class="acc-item"><div class="acc-num" style="color:#F5A623">'+(goodN?goodN.length:0)+'</div><div class="acc-label">好评</div></div>';var hb=$('meHbar');if(hb)hb.innerHTML=HBAR.filter(function(g){return g[2]!=='adminPage'||(me&&me.role==='admin');}).map(function(g){return g[2]==='logout'?'<div class="hbar-item" onclick="logout()"><div class="hi">'+g[0]+'</div><div class="ht">'+g[1]+'</div></div>':'<div class="hbar-item" onclick="goPage(\''+g[2]+'\')"><div class="hi">'+g[0]+'</div><div class="ht">'+g[1]+'</div></div>';}).join('');var ta=$('topAvatar');if(ta){ta.textContent=u.nickname?u.nickname[0]:'友';if(u.avatar_url)ta.innerHTML='<img src="'+esc(u.avatar_url)+'">';}}
function loadGroup(){var gb=$('groupBox');if(!gb)return;gb.innerHTML='<div class="dc-card"><div class="dc-h">💬 加入花学社交流群</div>'+GROUP_LINKS.map(function(g){return'<div class="his-card" onclick="location.href=\''+g.u+'\'"><span style="flex:1;font-size:14px">'+g.n+'</span><span style="color:#7B68EE">›</span></div>';}).join('')+'</div>';}
var GROUP_LINKS=[{n:'📢腾讯频道·花学社',u:'https://pd.qq.com/s/he8q7kzm3?b=9'},{n:'💬QQ群·花学交流群',u:'https://qun.qq.com/universal-share/share?ac=1&authKey=1aba71zRbWzorsI0HDNexE225xjziJnCD67y5Uc7ZVPOlQIXv3spYCzX27ZzAKWn&busi_data=eyJncm91cENvZGUiOiI3MzkzMzYwODEiLCJ0b2tlbiI6IjJGK2ZVci9NazE3TEVqZXVTcUhDN2hmQmMyQUNiWXA2MW0wejU2ekc4bytsb0RxZ1VOZDNFMm9qZWV5QjNwamkiLCJ1aW4iOiIyNjI5MTgxNzQ3In0%3D&data=qwk3yj6de7aK__jeez-Czl28fBpOJrnBaPPVnanfnIKpBn_WgrZJ-pTPiT-7KUczKFuimVrahitZ1bkfq4AJXA&svctype=4&tempid=h5_group_info'}];
async function loadHistory(){if(!me)return;var hl=$('historyList');if(!hl)return;try{var h=await api('/rest/v1/history?select=post_id&user_id=eq.'+me.id+'&order=viewed_at.desc&limit=20');if(!h||!h.length){hl.innerHTML='<div class="empty" style="padding:6px 0">暂无记录</div>';return;}var ids=h.map(function(x){return x.post_id;});var posts=await api('/rest/v1/posts?select=id,title&id=in.('+ids.join(',')+')&status=eq.published');hl.innerHTML=posts&&posts.length?posts.map(function(p){return'<div class="his-card" onclick="openPost('+p.id+')"><span style="flex:1;font-size:13px">'+esc(p.title)+'</span></div>';}).join(''):'<div class="empty" style="padding:6px 0">暂无</div>';}catch(e){hl.innerHTML='<div class="empty" style="padding:6px 0">暂无</div>';}}
function initEdit(){if(!me)return;var eb=$('eBio'),en=$('eName'),ee=$('editErr'),ap=$('avPreview');if(eb)eb.value=me.bio||'';if(en)en.value=me.nickname||'';if(ee)ee.textContent='';if(ap)ap.innerHTML='';}
async function saveProfile(){if(!me){toast('请先登录');needLogin();return;}var eb=$('eBio'),en=$('eName');if(!eb||!en)return;var bio=eb.value.trim(),nickname=en.value.trim();if(!nickname||nickname.length<2){var ee=$('editErr');if(ee)ee.textContent='用户名至少2个字';return;}try{var avatar_url=me.avatar_url||'';var ea=$('eAvatar');var fa=ea?ea._selected:null;if(fa)avatar_url=await uploadImg(fa);await dbU('profiles','id=eq.'+me.id,{bio:bio,nickname:nickname,avatar_url:avatar_url});me.bio=bio;me.nickname=nickname;me.avatar_url=avatar_url;toast('✅已保存');loadMe();goPage('mePage');}catch(e){var ee2=$('editErr');if(ee2)ee2.textContent='保存失败：'+e.message;}}
function initBeauty(){var cp=$('colorPalette');if(!cp)return;var colors=['#F0E6FF','#E8F1FF','#E6F7EC','#EFE9FF','#FFF7E0','#FFE9EC','#EAFBFF','#FFF0F5','#F0FFF0','#FFF5E6'];var cur=localStorage.getItem('hxs_bg')||'';cp.innerHTML=colors.map(function(c){return'<div style="width:36px;height:36px;border-radius:10px;background:'+c+';border:2px solid '+(cur===c?'#7B68EE':'#ddd')+';cursor:pointer" onclick="pickBgColor(\''+c+'\')"></div>';}).join('')+'<input type="color" value="#F0E6FF" style="width:36px;height:36px;border:none;cursor:pointer" onchange="pickBgColor(this.value)">';var bp=$('beautyPreview');if(bp)bp.innerHTML='';}
function pickBgColor(c){localStorage.setItem('hxs_bg',c);localStorage.setItem('hxs_bgimg','none');try{applyBg();}catch(e){}toast('🎨已应用');initBeauty();}
function resetBg(){localStorage.removeItem('hxs_bg');localStorage.removeItem('hxs_bgimg');try{applyBg();}catch(e){}toast('已恢复默认');initBeauty();}
async function loadInvite(){if(!me)return;var ib=$('inviteBox');if(!ib)return;ib.innerHTML='<div class="uinfo"><div style="font-size:14px;color:#999">我的邀请码</div><div style="font-size:30px;font-weight:800;color:#7B68EE;margin:6px 0;letter-spacing:3px">'+esc(me.invite_code||'---')+'</div><button class="btn" style="max-width:200px" onclick="copyInvite()">📋复制邀请码</button></div>';}
function copyInvite(){if(navigator.clipboard)navigator.clipboard.writeText(me.invite_code||'').then(function(){toast('✅已复制');}).catch(function(){toast('复制失败');});else toast('邀请码：'+(me.invite_code||''));}
async function loadInvited(){if(!me)return;var il=$('inviteList');if(!il)return;try{var d=await api('/rest/v1/profiles?select=nickname,avatar_url,level,created_at&invited_by=eq.'+me.id+'&order=created_at.desc&limit=50');il.innerHTML=(!d||!d.length)?'<div class="empty">还没有邀请到好友</div>':d.map(function(u){return'<div class="his-card"><div style="width:30px;height:30px;border-radius:50%;background:#eee;line-height:30px;text-align:center;overflow:hidden;flex-shrink:0">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'" style="width:100%;height:100%;object-fit:cover">':esc((u.nickname||'友')[0]))+'</div><span style="flex:1;font-size:13px">'+esc(u.nickname)+'</span><span style="font-size:11px;color:#999">'+fmtFull(u.created_at)+'</span></div>';}).join('');}catch(e){il.innerHTML='<div class="empty">加载失败</div>';}}
async function loadInfoCount(){if(!me)return;try{var r=await api('/rest/v1/notifications?user_id=eq.'+me.id+'&is_read=eq.false&select=id');var tb=$('topBadge');if(!tb)return;if(r&&r.length){tb.textContent=r.length;tb.style.display='inline';}else{tb.style.display='none';}}catch(e){}}
async function loadInfo(){if(!me){var il=$('infoList');if(il)il.innerHTML='<div class="empty">请先登录</div>';return;}try{var s=await api('/rest/v1/notification_settings?user_id=eq.'+me.id+'&limit=1');if(!s||!s.length){await dbI('notification_settings',{user_id:me.id});s=[{like_on:true,fav_on:true,follow_on:true,reward_on:true}];}var sw={like:$('swLike'),fav:$('swFav'),follow:$('swFollow'),reward:$('swReward')};if(sw.like)sw.like.classList.toggle('on',s[0].like_on);if(sw.fav)sw.fav.classList.toggle('on',s[0].fav_on);if(sw.follow)sw.follow.classList.toggle('on',s[0].follow_on);if(sw.reward)sw.reward.classList.toggle('on',s[0].reward_on);loadInfo2(infoType);}catch(e){}}
async function toggleSet(k,el){if(!me)return;var on=!el.classList.contains('on');el.classList.toggle('on',on);try{var key=(k==='like'?'like_on':k==='fav'?'fav_on':k==='follow'?'follow_on':'reward_on');var body={};body[key]=on;var s=await api('/rest/v1/notification_settings?user_id=eq.'+me.id+'&limit=1');if(!s||!s.length){await dbI('notification_settings',{user_id:me.id});}await dbU('notification_settings','user_id=eq.'+me.id,body);}catch(e){}}
async function loadInfo2(type){infoType=type;var n1=$('nt1'),n2=$('nt2'),n3=$('nt3');if(n1)n1.classList.toggle('on',type==='interact');if(n2)n2.classList.toggle('on',type==='official');if(n3)n3.classList.toggle('on',type==='comment');var il=$('infoList');if(!il)return;il.innerHTML='<div class="empty">加载中...</div>';try{var d=await api('/rest/v1/notifications?user_id=eq.'+me.id+'&order=created_at.desc&limit=50');if(!d||!d.length){il.innerHTML='<div class="empty">还没有消息</div>';return;}var filtered=d.filter(function(n){if(type==='interact')return n.type==='like'||n.type==='fav'||n.type==='follow';if(type==='official')return n.type==='official'||n.type==='punish'||n.type==='coin'||n.type==='reward';return n.type==='comment';});il.innerHTML=filtered.length?filtered.map(function(n){return'<div class="notif-item '+(n.is_read?'':'unread')+'"><span style="font-size:18px">'+(n.type==='like'?'👍':n.type==='fav'?'⭐':n.type==='follow'?'👥':n.type==='comment'?'💬':n.type==='punish'?'⚠️':'📢')+'</span><div style="flex:1"><div style="font-size:13px">'+esc(n.content)+'</div><div style="font-size:11px;color:#bbb;margin-top:2px">'+fmt(n.created_at)+'</div></div></div>';}).join(''):'<div class="empty">该分类暂无消息</div>';await dbU('notifications','user_id=eq.'+me.id,{is_read:true});loadInfoCount();}catch(e){il.innerHTML='<div class="empty">加载失败</div>';}}
async function loadSign(){var sb=$('signBox');if(!sb)return;try{var d=await api('/rest/v1/checkins?user_id=eq.'+me.id+'&order=checkin_date.desc&limit=7');var today=new Date().toISOString().slice(0,10);var done=d&&d[0]&&d[0].checkin_date===today;var streak=d&&d[0]?d[0].streak:0;var total=await api('/rest/v1/checkins?user_id=eq.'+me.id+'&select=id');sb.innerHTML='<div style="font-size:18px;font-weight:700;margin-bottom:4px">累计签到：<span style="color:#7B68EE">'+(total?total.length:0)+'天</span> · 连续：<span style="color:#ff9500">'+streak+'天</span></div>'+(done?'<div style="color:#999;padding:14px 0">今天已经签过啦</div>':'<button class="btn" style="max-width:220px" onclick="doCheckin()">📅立即签到</button>');if(done)loadSignRank();}catch(e){sb.innerHTML='<div class="empty">加载失败</div>';}}
async function doCheckin(){try{var r=await dbI('checkins',{user_id:me.id});toast('✅签到成功！连续'+r[0].streak+'天，+'+r[0].reward+'硬币');me=await fetchMe();loadSign();}catch(e){toast(e.message&&e.message.indexOf('23505')>-1?'今天已经签过啦':'签到失败');}}
async function loadSignRank(){var sr=$('signRank'),srl=$('signRankList');if(!sr||!srl)return;sr.style.display='block';try{var d=await api('/rest/v1/checkins?select=*,user_id(nickname,avatar_url,level)&checkin_date=eq.'+new Date().toISOString().slice(0,10)+'&order=created_at.asc&limit=50');srl.innerHTML=(!d||!d.length)?'<div class="empty">今日暂无签到</div>':d.map(function(c,i){var u=c.user_id||{};return'<div class="rank-item"><div class="rank-no '+(i<3?'top'+(i+1):'')+'">'+(i+1)+'</div><div style="width:30px;height:30px;border-radius:50%;background:#eee;line-height:30px;text-align:center;overflow:hidden;flex-shrink:0;margin-left:6px">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'" style="width:100%;height:100%;object-fit:cover">':esc((u.nickname||'友')[0]))+'</div><div style="flex:1;margin-left:8px"><div style="font-size:13px">'+esc(u.nickname||'')+'</div><div style="font-size:10px;color:#bbb">'+String(c.created_at).slice(11,19)+'</div></div><div style="font-size:11px;color:#999">'+c.streak+'天</div></div>';}).join('');}catch(e){srl.innerHTML='<div class="empty">排行加载失败</div>';}}
async function loadRank2(type){rank=type;try{var tg=$('tabGood'),tl=$('tabLike'),tv=$('tabLevel');if(tg)tg.classList.toggle('on',type==='good');if(tl)tl.classList.toggle('on',type==='like');if(tv)tv.classList.toggle('on',type==='level');}catch(e){}var rl=$('rankList'),mr=$('myRank');if(!rl)return;rl.innerHTML='<div class="empty">加载中...</div>';try{var data;if(type==='good')data=await dbR('rank_good',{});else if(type==='like')data=await dbR('rank_like',{});else data=await api('/rest/v1/profiles?select=*&order=level.desc,exp.desc&limit=50');if(!data)data=[];if(mr){var myRank=-1;for(var i=0;i<data.length;i++){if(data[i].uid===me.id||data[i].id===me.id){myRank=i+1;break;}}mr.innerHTML=me?'<div class="sticky-rank"><div class="rank-no">'+(myRank>0?myRank:'未上榜')+'</div><div style="width:30px;height:30px;border-radius:50%;background:#eee;line-height:30px;text-align:center;overflow:hidden;margin-left:6px;flex-shrink:0">'+(me.avatar_url?'<img src="'+esc(me.avatar_url)+'" style="width:100%;height:100%;object-fit:cover">':esc((me.nickname||'友')[0]))+'</div><div style="flex:1;margin-left:8px"><div style="font-size:13px;font-weight:600">'+esc(me.nickname)+'</div><div style="font-size:10px;color:#999">'+esc(me.bio||'')+'</div></div><div style="font-size:13px;color:#7B68EE;font-weight:600">'+(type==='good'?'❤️'+(myRank>0?data[myRank-1].good_total:0):type==='like'?'👍'+(myRank>0?data[myRank-1].like_total:0):'Lv'+me.level)+'</div></div>':'';}
var showGood=function(u,i){return'<div class="rank-item"><div class="rank-no '+(i<3?'top'+(i+1):'')+'">'+(i+1)+'</div><div style="width:30px;height:30px;border-radius:50%;background:#eee;line-height:30px;text-align:center;overflow:hidden;flex-shrink:0;margin-left:6px;cursor:pointer" onclick="openUser(\''+u.uid+'\')">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'" style="width:100%;height:100%;object-fit:cover">':esc((u.nickname||'友')[0]))+'</div><div style="flex:1;margin-left:8px;cursor:pointer" onclick="openUser(\''+u.uid+'\')"><div style="font-size:13px">'+esc(u.nickname)+(u.role==='admin'?'<span class="tag-admin">管理</span>':'')+'</div><div style="font-size:10px;color:#999;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(u.bio||'')+'</div></div><div style="font-size:13px;color:#ff9500;font-weight:600">❤️'+u.good_total+'</div></div>';};
var showLike=function(u,i){return'<div class="rank-item"><div class="rank-no '+(i<3?'top'+(i+1):'')+'">'+(i+1)+'</div><div style="width:30px;height:30px;border-radius:50%;background:#eee;line-height:30px;text-align:center;overflow:hidden;flex-shrink:0;margin-left:6px;cursor:pointer" onclick="openUser(\''+u.uid+'\')">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'" style="width:100%;height:100%;object-fit:cover">':esc((u.nickname||'友')[0]))+'</div><div style="flex:1;margin-left:8px;cursor:pointer" onclick="openUser(\''+u.uid+'\')"><div style="font-size:13px">'+esc(u.nickname)+(u.role==='admin'?'<span class="tag-admin">管理</span>':'')+'</div><div style="font-size:10px;color:#999;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(u.bio||'')+'</div></div><div style="font-size:13px;color:#7B68EE;font-weight:600">👍'+u.like_total+'</div></div>';};
var showLv=function(u,i){return'<div class="rank-item"><div class="rank-no '+(i<3?'top'+(i+1):'')+'">'+(i+1)+'</div><div style="width:30px;height:30px;border-radius:50%;background:#eee;line-height:30px;text-align:center;overflow:hidden;flex-shrink:0;margin-left:6px;cursor:pointer" onclick="openUser(\''+u.id+'\')">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'" style="width:100%;height:100%;object-fit:cover">':esc((u.nickname||'友')[0]))+'</div><div style="flex:1;margin-left:8px;cursor:pointer" onclick="openUser(\''+u.id+'\')"><div style="font-size:13px">'+esc(u.nickname)+(u.role==='admin'?'<span class="tag-admin">管理</span>':'')+'</div><div style="font-size:10px;color:#999;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(u.bio||'')+'</div></div><div style="font-size:13px;color:#7B68EE;font-weight:600"><span class="lv" style="background:#7B68EE">Lv'+u.level+'</span>⚡'+u.exp+'</div></div>';};
rl.innerHTML=data.length?data.map(function(u,i){return type==='good'?showGood(u,i):type==='like'?showLike(u,i):showLv(u,i);}).join(''):'<div class="empty">暂无数据</div>';}catch(e){rl.innerHTML='<div class="empty">加载失败</div>';}}
async function loadFriends(t){friendType=t;var f1=$('ft1'),f2=$('ft2');if(f1)f1.classList.toggle('on',t==='following');if(f2)f2.classList.toggle('on',t==='fans');var fl=$('friendList');if(!fl)return;fl.innerHTML='<div class="empty">加载中...</div>';try{var data;if(t==='following'){var fs=await api('/rest/v1/followers?select=following_id&follower_id=eq.'+me.id+'&limit=200');if(!fs||!fs.length){fl.innerHTML='<div class="empty">还没有关注任何人</div>';return;}var ids=fs.map(function(f){return f.following_id;});data=await api('/rest/v1/profiles?select=*&id=in.('+ids.join(',')+')');}else{var fs2=await api('/rest/v1/followers?select=follower_id&following_id=eq.'+me.id+'&limit=200');if(!fs2||!fs2.length){fl.innerHTML='<div class="empty">还没有粉丝</div>';return;}var ids2=fs2.map(function(f){return f.follower_id;});data=await api('/rest/v1/profiles?select=*&id=in.('+ids2.join(',')+')');}if(!data)data=[];data.sort(function(a,b){return(a.nickname||'').localeCompare(b.nickname||'');});fl.innerHTML=data.length?data.map(function(u){return'<div class="his-card" style="cursor:pointer" onclick="openUser(\''+u.id+'\')"><div style="width:36px;height:36px;border-radius:50%;background:#eee;line-height:36px;text-align:center;overflow:hidden;flex-shrink:0">'+(u.avatar_url?'<img src="'+esc(u.avatar_url)+'" style="width:100%;height:100%;object-fit:cover">':esc((u.nickname||'友')[0]))+'</div><div style="flex:1;margin-left:10px"><div style="font-size:14px;font-weight:600">'+esc(u.nickname)+(u.role==='admin'?'<span class="tag-admin">管理</span>':'')+'</div><div style="font-size:11px;color:#999">'+esc(u.bio||'')+'</div></div></div>';}).join(''):'<div class="empty">暂无</div>';}catch(e){fl.innerHTML='<div class="empty">加载失败</div>';}}
function initPomo(){if(!$('ringOptions').innerHTML){$('ringOptions').innerHTML=['🔔 默认','📣 提醒','🎵 音乐','📳 振动'].map(function(r,i){return'<div class="chip '+(i===0?'on':'')+'" data-i="'+i+'" onclick="pickRing(this,'+i+')">'+r+'</div>';}).join('');}pomoRender();}
var pomoRing=0;
function pickRing(el,i){pomoRing=i;document.querySelectorAll('#ringOptions .chip').forEach(function(x){x.classList.remove('on');});el.classList.add('on');}
function pomoStart(){var b=$('pomoBtn');if(!b)return;if(pomoT){clearInterval(pomoT);pomoT=null;b.textContent='继续';var ps=$('pomoState');if(ps)ps.textContent='已暂停';return;}var dd=parseInt(($('pomoD')||{}).value)||0,h=parseInt(($('pomoH')||{}).value)||0,m=parseInt(($('pomoM')||{}).value)||0,s=parseInt(($('pomoS')||{}).value)||0;if(m>60)m=60;if(s>60)s=60;pomoL=dd*86400+h*3600+m*60+s;if(pomoL<=0){toast('请设置时间');return;}b.textContent='暂停';var ps2=$('pomoState');if(ps2)ps2.textContent='倒计时中…';pomoT=setInterval(function(){pomoL--;if(pomoL<=0){clearInterval(pomoT);pomoT=null;b.textContent='开始';var ps3=$('pomoState');if(ps3)ps3.textContent='⏰时间到！';try{if(navigator.vibrate)navigator.vibrate([200,100,200,100,200]);}catch(e){}toast('⏰时间到！');return;}pomoRender();},1000);}
function pomoReset(){if(pomoT){clearInterval(pomoT);pomoT=null;}var b=$('pomoBtn');if(b)b.textContent='开始';var ps=$('pomoState');if(ps)ps.textContent='自定义时间';pomoL=0;try{pomoRender();}catch(e){}}
function pomoRender(){var pt=$('pomoTime');if(!pt)return;var dd=Math.floor(pomoL/86400),h=Math.floor(pomoL%86400/3600),m=Math.floor(pomoL%3600/60),s=pomoL%60;pt.textContent=(dd>0?dd+'天':'')+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}
function renderCourses(){var cl=$('courseList');if(!cl)return;cl.innerHTML=COURSES.map(function(c,i){return'<div class="his-card" onclick="location.href=\''+c.u+'\'"><span style="flex:1;font-size:13px">'+(c.p==='bili'?'🔵':'🔴')+c.t+'</span><span style="font-size:11px;color:'+(c.p==='bili'?'#fb7299':'#161823')+'">'+(c.p==='bili'?'B站':'抖音')+'</span></div>';}).join('');}
async function favCourse(idx){if(!me){toast('请先登录');needLogin();return;}try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.course&target_id=eq.'+idx+'&limit=1');if(r&&r.length){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.course&target_id=eq.'+idx);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:'course',target_id:idx});toast('⭐已收藏');}}catch(e){toast('失败');}}
function showAt(){var sel=$('atSel');if(!sel)return;if(!me){sel.style.display='none';return;}try{api('/rest/v1/profiles?select=nickname,id&role=eq.admin&limit=50').then(function(admins){api('/rest/v1/followers?select=following_id&follower_id=eq.'+me.id+'&limit=200').then(function(follows){var list=[];if(admins)list=list.concat(admins.filter(function(a){return a.id!==me.id;}));if(follows&&follows.length){var ids=follows.map(function(f){return f.following_id;});api('/rest/v1/profiles?select=nickname,id&id=in.('+ids.join(',')+')').then(function(fs){if(fs)list=list.concat(fs.filter(function(f){return f.id!==me.id;}));list=list.filter(function(v,i,a){return a.findIndex(function(x){return x.id===v.id;})===i;});sel.innerHTML=list.length?list.map(function(u){return'<div class="at-i" onclick="insertAt(\''+esc(u.nickname)+'\')">@'+esc(u.nickname)+'</div>';}).join(''):'<div class="at-i">可@管理员及关注的人</div>';sel.style.display='block';});}else{sel.innerHTML='<div class="at-i">可@管理员及关注的人</div>';sel.style.display='block';}}).catch(function(){sel.innerHTML='<div class="at-i">可@管理员及关注的人</div>';sel.style.display='block';});}).catch(function(){sel.style.display='none';});}catch(e){sel.style.display='none';}}
function insertAt(name){var inp=$('pContent')||$('cmInput');if(inp)inp.value+='@'+name+' ';var as=$('atSel');if(as)as.style.display='none';if(inp&&inp.id==='cmInput')inp.focus();}
function extractLink(el){var out=$(el.id==='resLink'?'resLinkOut':'resLinkOut2');if(!out)return;var m=el.value.match(/https?:\/\/[^\s，。；、""'']+/g);if(m&&m.length){out.textContent=m[0];el.dataset.link=m[0];}else{out.textContent='';el.dataset.link='';}}
function parseApk(inp){var f=inp.files&&inp.files[0];var box=$('apkInfo');if(!f||!box)return;var sizeMB=(f.size/1024/1024).toFixed(1);var name=f.name.replace(/\.apk$/i,'');box.innerHTML='<div style="background:#f7f8fa;border-radius:8px;padding:10px;font-size:13px"><div>📦 '+esc(name)+'</div><div style="font-size:11px;color:#999;margin-top:2px">大小：'+sizeMB+' MB</div><div class="tip">（图标/包名/版本自动读取需要解析工具，当前版本自动填入名称与大小）</div></div>';var rt=$('resTitle');if(rt)rt.value=name;var rs=$('resSize');if(rs)rs.value=sizeMB+'MB';inp._apkInfo={name:name,size:sizeMB};}
function initResPost(){var rc=$('resTypeChips');if(!rc)return;rc.innerHTML=[['video','🎬教程视频'],['app','📱应用']].map(function(x){return'<div class="chip '+(x[0]===resType?'on':'')+'" onclick="pickResType(this,\''+x[0]+'\')">'+x[1]+'</div>';}).join('');var rv=$('resPostVideo'),ra=$('resPostApp');if(rv)rv.style.display=resType==='video'?'block':'none';if(ra)ra.style.display=resType==='app'?'block':'none';var re=$('resErr');if(re)re.textContent='';}
function pickResType(el,k){resType=k;document.querySelectorAll('#resTypeChips .chip').forEach(function(x){x.classList.remove('on');});el.classList.add('on');var rv=$('resPostVideo'),ra=$('resPostApp');if(rv)rv.style.display=k==='video'?'block':'none';if(ra)ra.style.display=k==='app'?'block':'none';}
async function submitRes(){if(!me||me.role!=='admin'){toast('仅管理员');return;}var title,desc,link,size=null,icon='';if(resType==='video'){var rt=$('resTitle'),rd=$('resDesc'),rl=$('resLink');if(!rt||!rd||!rl)return;title=rt.value.trim();desc=rd.value.trim();link=(rl.dataset&&rl.dataset.link)||rl.value.trim();if(!title||!link){var re=$('resErr');if(re)re.textContent='请填标题和链接';return;}}else{var rt2=$('resTitle'),rd2=$('resDesc2'),rl2=$('resLink2');if(!rt2||!rd2||!rl2)return;title=rt2.value.trim();desc=rd2.value.trim();link=(rl2.dataset&&rl2.dataset.link)||rl2.value.trim();if(!title||!link){var re2=$('resErr');if(re2)re2.textContent='请填标题和链接';return;}var rs=$('resSize');if(rs)size=rs.value.trim()||null;}try{await dbI('resources',{title:title,description:desc,type:resType,link:link,icon:icon,size_mb:size,created_by:me.id});toast('✅已发布');var all=[$('resTitle'),$('resDesc'),$('resLink'),$('resDesc2'),$('resLink2'),$('resSize')];all.forEach(function(el){if(el){el.value='';el.dataset&&(el.dataset.link='');}});goPage('resourcePage');}catch(e){var re3=$('resErr');if(re3)re3.textContent='失败：'+e.message;}}
async function loadRes(type){resType=type;try{var rt1=$('resTab1'),rt2=$('resTab2');if(rt1)rt1.classList.toggle('on',type==='video');if(rt2)rt2.classList.toggle('on',type==='app');}catch(e){}var rl=$('resList');if(!rl)return;rl.innerHTML='<div class="empty">加载中...</div>';try{var d=await api('/rest/v1/resources?select=*&type=eq.'+type+'&order=created_at.desc');if(!d||!d.length){rl.innerHTML='<div class="empty">暂无内容</div>';return;}var isAdmin=me&&me.role==='admin';if(type==='video'){rl.innerHTML=d.map(function(r){return'<div class="video-card"><div class="video-cover" onclick="window.open(\''+esc(r.link)+'\')">▶️</div><div class="video-info"><div class="vt">'+esc(r.title)+'</div><div class="vs">'+esc(r.description||'')+'</div>'+(isAdmin?'<div style="margin-top:4px"><span style="color:#e5484d;font-size:11px;cursor:pointer" onclick="delRes('+r.id+')">🗑删除</span></div>':'')+'</div></div>';}).join('');}else{rl.innerHTML=d.map(function(r){return'<div class="app-card" onclick="openAppDetail('+r.id+')"><div class="ac-top"><div class="ac-icon" style="background:#eee;text-align:center;line-height:48px;font-size:22px">'+(r.icon?'<img src="'+esc(r.icon)+'" class="ac-icon">':'📱')+'</div><div><div class="ac-title">'+esc(r.title)+'<span class="lv" style="margin-left:4px;background:#ff9500">'+(r.size_mb||'')+'</span></div><div class="ac-sub">'+esc(r.description||'')+'·📥'+(r.downloads||0)+'次</div>'+(isAdmin?'<div style="margin-top:4px"><span style="color:#e5484d;font-size:11px;cursor:pointer" onclick="event.stopPropagation();delRes('+r.id+')">🗑删除</span></div>':'')+'</div></div></div>';}).join('');}}catch(e){rl.innerHTML='<div class="empty">加载失败</div>';}}
async function delRes(rid){if(!confirm('确定删除？'))return;try{await dbD('resources','id=eq.'+rid);toast('已删除');loadRes(resType);}catch(e){toast('失败');}}
async function openAppDetail(id){try{var r=await api('/rest/v1/resources?id=eq.'+id);var d=r&&r[0];if(!d)return;var fav=me?await isFav('app',d.id):false;var ab=$('appDetailBox');if(!ab)return;ab.innerHTML='<div style="background:#fff;border-radius:12px;padding:16px;text-align:center;margin-bottom:10px">'+(d.icon?'<img src="'+esc(d.icon)+'" style="width:72px;height:72px;border-radius:14px;object-fit:cover;margin-bottom:8px">':'<div style="width:72px;height:72px;border-radius:14px;background:#eee;line-height:72px;margin:0 auto 8px;font-size:28px">📱</div>')+'<div style="font-size:17px;font-weight:700">'+esc(d.title)+'</div></div><div style="background:#fff;border-radius:12px;padding:14px;font-size:13px;line-height:1.7;color:#444;margin-bottom:10px">'+esc(d.description||'暂无介绍')+'</div><div class="stat-card"><div><div class="stat-num">'+(d.downloads||0)+'</div><div class="stat-label">下载</div></div><div><div class="stat-num">'+(d.size_mb||'--')+'</div><div class="stat-label">大小</div></div></div><div class="detail-actions"><button class="action-btn '+(fav?'on':'')+'" style="border-color:#7B68EE;color:#7B68EE" onclick="favRes(\'app\','+d.id+')">⭐'+(fav?'已收藏':'收藏')+'</button><button class="action-btn" style="border-color:#ff9500;color:#ff9500" onclick="window.open(\''+esc(d.link)+'\')">🔗前往下载</button>'+(me&&me.role==='admin'?'<button class="action-btn" style="color:#e5484d" onclick="delRes('+d.id+')">🗑删除</button>':'')+'</div>';goPage('appDetailPage');}catch(e){toast('加载失败');}}
async function favRes(type,rid){if(!me){toast('请先登录');needLogin();return;}try{var r=await api('/rest/v1/favorites?user_id=eq.'+me.id+'&target_type=eq.'+type+'&target_id=eq.'+rid+'&limit=1');if(r&&r.length){await dbD('favorites','user_id=eq.'+me.id+'&target_type=eq.'+type+'&target_id=eq.'+rid);toast('已取消');}else{await dbI('favorites',{user_id:me.id,target_type:type,target_id:rid});toast('⭐已收藏');}loadRes(resType);}catch(e){toast('失败');}}
async function loadAdmin(tab){try{var a1=$('aTab1'),a2=$('aTab2');if(a1)a1.classList.toggle('on',tab==='reports');if(a2)a2.classList.toggle('on',tab==='punish');}catch(e){}var ab=$('adminBox');if(!ab)return;if(tab==='reports'){try{var d=await api('/rest/v1/reports?status=eq.pending&order=created_at.desc');if(!d||!d.length){ab.innerHTML='<div class="empty">没有待处理举报🎉</div>';return;}var h='<div class="tip" style="margin-bottom:8px">共'+d.length+'条</div>';for(var i=0;i<d.length;i++){var r=d[i],target='',content='',author='';try{if(r.target_type==='post'){var p=await api('/rest/v1/posts?select=*,author_id(nickname)&id=eq.'+r.target_id);if(p&&p[0]){target='帖子：'+p[0].title;content=p[0].content;author=p[0].author_id?p[0].author_id.nickname:'';}}else{var c=await api('/rest/v1/comments?select=*,author_id(nickname)&id=eq.'+r.target_id);if(c&&c[0]){target='评论#'+r.target_id;content=c[0].content;author=c[0].author_id?c[0].author_id.nickname:'';}}}catch(e){}h+='<div class="comment-box"><div style="font-size:13px;font-weight:600">🚩'+esc(r.reason)+'</div><div style="font-size:11px;color:#999;margin:4px 0">'+esc(target)+' · 作者：'+esc(author)+'</div><div style="font-size:12px;color:#555;background:#f7f8fa;border-radius:8px;padding:8px;margin:8px 0;cursor:pointer" onclick="'+(r.target_type==='post'?'openPost('+r.target_id+')':'')+'">'+esc(content)+'</div><div style="display:flex;gap:8px"><button class="btn" style="background:#999;flex:1" onclick="handleReport('+r.id+',\'ignore\')">忽略</button><button class="btn" style="flex:1" onclick="handleReport('+r.id+',\'delete\')">删内容</button><button class="btn" style="background:#e5484d;flex:1" onclick="handleReport('+r.id+',\'punish\')">删+扣分</button></div></div>';}ab.innerHTML=h;}catch(e){ab.innerHTML='<div class="empty">加载失败</div>';}}else{ab.innerHTML='<div class="tip" style="margin-bottom:8px">按用户名或QQ号查找用户</div><input id="punishQQ" class="inp" placeholder="输入用户名或QQ号"><button class="btn" onclick="findUser()">查找</button><div id="userInfo" style="margin-top:10px"></div><div style="margin-top:12px;background:#fff;border-radius:10px;padding:12px"><div style="font-size:13px;font-weight:600;margin-bottom:8px">📢 群发通知</div><textarea id="broadcastText" class="inp" style="height:50px" placeholder="通知内容"></textarea><div style="display:flex;gap:8px"><button class="btn" style="flex:1" onclick="broadcast(\'all\')">发给全体</button><button class="btn btn-plain" style="flex:1" onclick="broadcast(\'admins\')">发给管理员</button></div></div>';}}
async function broadcast(t){var bt=$('broadcastText');if(!bt)return;var c=bt.value.trim();if(!c){toast('请输入通知内容');return;}try{var r=await dbR('broadcast_notification',{p_content:c,p_target:t});toast(r==='OK'?'✅已群发':r);bt.value='';}catch(e){toast('失败');}}
async function findUser(){var pq=$('punishQQ');if(!pq)return;var kw=pq.value.trim();try{var d;if(/^\d{5,12}$/.test(kw)){d=await api('/rest/v1/profiles?select=*&qq=eq.'+kw+'&limit=1');}else{d=await api('/rest/v1/profiles?select=*&nickname=eq.'+kw+'&limit=1');}var ui=$('userInfo');if(!ui)return;if(!d||!d.length){ui.innerHTML='<div class="empty">没找到</div>';return;}var u=d[0];ui.innerHTML='<div class="comment-box"><div style="font-weight:600">👤'+esc(u.nickname)+(u.role==='admin'?'<span class="tag-admin">管理</span>':'')+'</div><div style="font-size:12px;color:#555;background:#f7f8fa;border-radius:8px;padding:8px;margin:6px 0">QQ：'+esc(u.qq||'-')+' · Lv'+u.level+'·🪙'+u.coins+'·💯'+u.credit+(u.is_banned?'·⛔已封号':'')+'</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" style="background:#e5484d" onclick="punish(\''+u.id+'\',\'credit\',prompt(\'扣多少分？\',\'10\'))">扣分</button><button class="btn" onclick="punish(\''+u.id+'\',\'mute\',prompt(\'禁言几天？\',\'1\'))">禁言</button><button class="btn" style="background:#e5484d" onclick="punish(\''+u.id+'\',\'ban\',0)">封号</button><button class="btn" style="background:#e5484d" onclick="punish(\''+u.id+'\',\'device_ban\',0)">封设备</button><button class="btn" style="background:#999" onclick="punish(\''+u.id+'\',\'unban\',0)">解封</button><button class="btn" style="background:#999" onclick="punish(\''+u.id+'\',\'unmute\',0)">解禁</button><button class="btn" style="background:#999" onclick="punish(\''+u.id+'\',\'unde\',0)">解封设备</button><button class="btn" style="background:#07c160" onclick="punish(\''+u.id+'\',\'addcredit\',prompt(\'加多少分？\',\'5\'))">加信誉分</button><button class="btn" style="background:#07c160" onclick="punish(\''+u.id+'\',\'addcoin\',prompt(\'给多少硬币？\',\'10\'))">奖硬币</button></div></div>';}catch(e){var ui2=$('userInfo');if(ui2)ui2.innerHTML='<div class="empty">查询失败</div>';}}
async function punish(uid,action,amount){try{var r=await dbR('admin_punish',{p_user_id:uid,p_action:action,p_amount:parseInt(amount)||0,p_detail:action});toast(r==='OK'?'✅已执行':('⚠️'+r));}catch(e){toast('失败');}}
async function handleReport(rid,act){try{if(act==='ignore'){await dbU('reports','id=eq.'+rid,{status:'ignored'});toast('已忽略');}else{var r=await api('/rest/v1/reports?id=eq.'+rid);var rep=r&&r[0];if(rep){if(rep.target_type==='post'){var p=await api('/rest/v1/posts?id=eq.'+rep.target_id);if(p&&p[0]){if(act==='punish')await dbR('admin_punish',{p_user_id:p[0].author_id,p_action:'credit',p_amount:10,p_detail:'举报成立'});await dbR('delete_post',{pid:rep.target_id});}}else{await dbR('delete_comment',{cid:rep.target_id});}await dbU('reports','id=eq.'+rid,{status:'handled'});if(rep.reporter_id)dbR('reward_report',{p_reporter_id:rep.reporter_id}).catch(function(){});toast('✅已处理');}}loadAdmin('reports');}catch(e){toast('处理失败');}}
try{drawCaptcha();}catch(e){}
try{if(curUser2())showMain();else goPage('loginPage');}catch(e){goPage('loginPage');}